//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DB_40114_codeclubModel", "FK_resourceCategory_category", "category", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(webComponents.Models.category), "resourceCategory", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(webComponents.Models.resourceCategory), true)]
[assembly: EdmRelationshipAttribute("DB_40114_codeclubModel", "FK_resource_resource", "resource", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(webComponents.Models.resource), "resource1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(webComponents.Models.resource), true)]
[assembly: EdmRelationshipAttribute("DB_40114_codeclubModel", "FK_resourceCategory_resource", "resource", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(webComponents.Models.resource), "resourceCategory", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(webComponents.Models.resourceCategory), true)]
[assembly: EdmRelationshipAttribute("DB_40114_codeclubModel", "FK_resourceHighlight_resource", "resource", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(webComponents.Models.resource), "resourceHighlight", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(webComponents.Models.resourceHighlight), true)]

#endregion

namespace webComponents.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class context : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new context object using the connection string found in the 'context' section of the application configuration file.
        /// </summary>
        public context() : base("name=context", "context")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new context object.
        /// </summary>
        public context(string connectionString) : base(connectionString, "context")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new context object.
        /// </summary>
        public context(EntityConnection connection) : base(connection, "context")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<category> categories
        {
            get
            {
                if ((_categories == null))
                {
                    _categories = base.CreateObjectSet<category>("categories");
                }
                return _categories;
            }
        }
        private ObjectSet<category> _categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<login> logins
        {
            get
            {
                if ((_logins == null))
                {
                    _logins = base.CreateObjectSet<login>("logins");
                }
                return _logins;
            }
        }
        private ObjectSet<login> _logins;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<resource> resources
        {
            get
            {
                if ((_resources == null))
                {
                    _resources = base.CreateObjectSet<resource>("resources");
                }
                return _resources;
            }
        }
        private ObjectSet<resource> _resources;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<resourceCategory> resourceCategories
        {
            get
            {
                if ((_resourceCategories == null))
                {
                    _resourceCategories = base.CreateObjectSet<resourceCategory>("resourceCategories");
                }
                return _resourceCategories;
            }
        }
        private ObjectSet<resourceCategory> _resourceCategories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<resourceHighlight> resourceHighlights
        {
            get
            {
                if ((_resourceHighlights == null))
                {
                    _resourceHighlights = base.CreateObjectSet<resourceHighlight>("resourceHighlights");
                }
                return _resourceHighlights;
            }
        }
        private ObjectSet<resourceHighlight> _resourceHighlights;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocategories(category category)
        {
            base.AddObject("categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the logins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTologins(login login)
        {
            base.AddObject("logins", login);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the resources EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToresources(resource resource)
        {
            base.AddObject("resources", resource);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the resourceCategories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToresourceCategories(resourceCategory resourceCategory)
        {
            base.AddObject("resourceCategories", resourceCategory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the resourceHighlights EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToresourceHighlights(resourceHighlight resourceHighlight)
        {
            base.AddObject("resourceHighlights", resourceHighlight);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_40114_codeclubModel", Name="category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new category object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static category Createcategory(global::System.Int32 id)
        {
            category category = new category();
            category.ID = id;
            return category;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_40114_codeclubModel", "FK_resourceCategory_category", "resourceCategory")]
        public EntityCollection<resourceCategory> resourceCategories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<resourceCategory>("DB_40114_codeclubModel.FK_resourceCategory_category", "resourceCategory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<resourceCategory>("DB_40114_codeclubModel.FK_resourceCategory_category", "resourceCategory", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_40114_codeclubModel", Name="login")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class login : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new login object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static login Createlogin(global::System.Int32 id)
        {
            login login = new login();
            login.ID = id;
            return login;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_40114_codeclubModel", Name="resource")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class resource : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new resource object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static resource Createresource(global::System.Int32 id)
        {
            resource resource = new resource();
            resource.ID = id;
            return resource;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> parentID
        {
            get
            {
                return _parentID;
            }
            set
            {
                OnparentIDChanging(value);
                ReportPropertyChanging("parentID");
                _parentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("parentID");
                OnparentIDChanged();
            }
        }
        private Nullable<global::System.Int32> _parentID;
        partial void OnparentIDChanging(Nullable<global::System.Int32> value);
        partial void OnparentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_40114_codeclubModel", "FK_resource_resource", "resource1")]
        public EntityCollection<resource> resource1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<resource>("DB_40114_codeclubModel.FK_resource_resource", "resource1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<resource>("DB_40114_codeclubModel.FK_resource_resource", "resource1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_40114_codeclubModel", "FK_resource_resource", "resource")]
        public resource resource2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<resource>("DB_40114_codeclubModel.FK_resource_resource", "resource").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<resource>("DB_40114_codeclubModel.FK_resource_resource", "resource").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<resource> resource2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<resource>("DB_40114_codeclubModel.FK_resource_resource", "resource");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<resource>("DB_40114_codeclubModel.FK_resource_resource", "resource", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_40114_codeclubModel", "FK_resourceCategory_resource", "resourceCategory")]
        public EntityCollection<resourceCategory> resourceCategories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<resourceCategory>("DB_40114_codeclubModel.FK_resourceCategory_resource", "resourceCategory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<resourceCategory>("DB_40114_codeclubModel.FK_resourceCategory_resource", "resourceCategory", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_40114_codeclubModel", "FK_resourceHighlight_resource", "resourceHighlight")]
        public EntityCollection<resourceHighlight> resourceHighlights
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<resourceHighlight>("DB_40114_codeclubModel.FK_resourceHighlight_resource", "resourceHighlight");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<resourceHighlight>("DB_40114_codeclubModel.FK_resourceHighlight_resource", "resourceHighlight", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_40114_codeclubModel", Name="resourceCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class resourceCategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new resourceCategory object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static resourceCategory CreateresourceCategory(global::System.Int32 id)
        {
            resourceCategory resourceCategory = new resourceCategory();
            resourceCategory.ID = id;
            return resourceCategory;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> resourceID
        {
            get
            {
                return _resourceID;
            }
            set
            {
                OnresourceIDChanging(value);
                ReportPropertyChanging("resourceID");
                _resourceID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("resourceID");
                OnresourceIDChanged();
            }
        }
        private Nullable<global::System.Int32> _resourceID;
        partial void OnresourceIDChanging(Nullable<global::System.Int32> value);
        partial void OnresourceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> categoryID
        {
            get
            {
                return _categoryID;
            }
            set
            {
                OncategoryIDChanging(value);
                ReportPropertyChanging("categoryID");
                _categoryID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("categoryID");
                OncategoryIDChanged();
            }
        }
        private Nullable<global::System.Int32> _categoryID;
        partial void OncategoryIDChanging(Nullable<global::System.Int32> value);
        partial void OncategoryIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_40114_codeclubModel", "FK_resourceCategory_category", "category")]
        public category category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<category>("DB_40114_codeclubModel.FK_resourceCategory_category", "category").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<category>("DB_40114_codeclubModel.FK_resourceCategory_category", "category").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<category> categoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<category>("DB_40114_codeclubModel.FK_resourceCategory_category", "category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<category>("DB_40114_codeclubModel.FK_resourceCategory_category", "category", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_40114_codeclubModel", "FK_resourceCategory_resource", "resource")]
        public resource resource
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<resource>("DB_40114_codeclubModel.FK_resourceCategory_resource", "resource").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<resource>("DB_40114_codeclubModel.FK_resourceCategory_resource", "resource").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<resource> resourceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<resource>("DB_40114_codeclubModel.FK_resourceCategory_resource", "resource");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<resource>("DB_40114_codeclubModel.FK_resourceCategory_resource", "resource", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_40114_codeclubModel", Name="resourceHighlight")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class resourceHighlight : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new resourceHighlight object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static resourceHighlight CreateresourceHighlight(global::System.Int32 id)
        {
            resourceHighlight resourceHighlight = new resourceHighlight();
            resourceHighlight.ID = id;
            return resourceHighlight;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> resourceID
        {
            get
            {
                return _resourceID;
            }
            set
            {
                OnresourceIDChanging(value);
                ReportPropertyChanging("resourceID");
                _resourceID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("resourceID");
                OnresourceIDChanged();
            }
        }
        private Nullable<global::System.Int32> _resourceID;
        partial void OnresourceIDChanging(Nullable<global::System.Int32> value);
        partial void OnresourceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String colorCode
        {
            get
            {
                return _colorCode;
            }
            set
            {
                OncolorCodeChanging(value);
                ReportPropertyChanging("colorCode");
                _colorCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("colorCode");
                OncolorCodeChanged();
            }
        }
        private global::System.String _colorCode;
        partial void OncolorCodeChanging(global::System.String value);
        partial void OncolorCodeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_40114_codeclubModel", "FK_resourceHighlight_resource", "resource")]
        public resource resource
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<resource>("DB_40114_codeclubModel.FK_resourceHighlight_resource", "resource").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<resource>("DB_40114_codeclubModel.FK_resourceHighlight_resource", "resource").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<resource> resourceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<resource>("DB_40114_codeclubModel.FK_resourceHighlight_resource", "resource");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<resource>("DB_40114_codeclubModel.FK_resourceHighlight_resource", "resource", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
