//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DB_40114_codeclubModel1", "FK_testreview_test", "test", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ModelsProject.Models.test), "testreview", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ModelsProject.Models.testreview), true)]

#endregion

namespace ModelsProject.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class context : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new context object using the connection string found in the 'context' section of the application configuration file.
        /// </summary>
        public context() : base("name=context", "context")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new context object.
        /// </summary>
        public context(string connectionString) : base(connectionString, "context")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new context object.
        /// </summary>
        public context(EntityConnection connection) : base(connection, "context")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<test> test
        {
            get
            {
                if ((_test == null))
                {
                    _test = base.CreateObjectSet<test>("test");
                }
                return _test;
            }
        }
        private ObjectSet<test> _test;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<testreview> testreview
        {
            get
            {
                if ((_testreview == null))
                {
                    _testreview = base.CreateObjectSet<testreview>("testreview");
                }
                return _testreview;
            }
        }
        private ObjectSet<testreview> _testreview;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the test EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotest(test test)
        {
            base.AddObject("test", test);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the testreview EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotestreview(testreview testreview)
        {
            base.AddObject("testreview", testreview);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<Nullable<global::System.Int32>> TESTPROC()
        {
            return base.ExecuteFunction<Nullable<global::System.Int32>>("TESTPROC");
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_40114_codeclubModel1", Name="test")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class test : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new test object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static test Createtest(global::System.Int32 id)
        {
            test test = new test();
            test.id = id;
            return test;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_40114_codeclubModel1", "FK_testreview_test", "testreview")]
        public EntityCollection<testreview> testreview
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<testreview>("DB_40114_codeclubModel1.FK_testreview_test", "testreview");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<testreview>("DB_40114_codeclubModel1.FK_testreview_test", "testreview", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_40114_codeclubModel1", Name="testreview")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class testreview : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new testreview object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static testreview Createtestreview(global::System.Int32 id)
        {
            testreview testreview = new testreview();
            testreview.id = id;
            return testreview;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> testid
        {
            get
            {
                return _testid;
            }
            set
            {
                OntestidChanging(value);
                ReportPropertyChanging("testid");
                _testid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("testid");
                OntestidChanged();
            }
        }
        private Nullable<global::System.Int32> _testid;
        partial void OntestidChanging(Nullable<global::System.Int32> value);
        partial void OntestidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> rate
        {
            get
            {
                return _rate;
            }
            set
            {
                OnrateChanging(value);
                ReportPropertyChanging("rate");
                _rate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rate");
                OnrateChanged();
            }
        }
        private Nullable<global::System.Int32> _rate;
        partial void OnrateChanging(Nullable<global::System.Int32> value);
        partial void OnrateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_40114_codeclubModel1", "FK_testreview_test", "test")]
        public test test
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<test>("DB_40114_codeclubModel1.FK_testreview_test", "test").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<test>("DB_40114_codeclubModel1.FK_testreview_test", "test").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<test> testReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<test>("DB_40114_codeclubModel1.FK_testreview_test", "test");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<test>("DB_40114_codeclubModel1.FK_testreview_test", "test", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
