//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingServiceClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAccountingV1")]
    public interface IAccountingV1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountingV1/getInvoiceServicesSumAmt", ReplyAction="http://tempuri.org/IAccountingV1/getInvoiceServicesSumAmtResponse")]
        string getInvoiceServicesSumAmt();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountingV1Channel : AccountingServiceClient.ServiceReference1.IAccountingV1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountingV1Client : System.ServiceModel.ClientBase<AccountingServiceClient.ServiceReference1.IAccountingV1>, AccountingServiceClient.ServiceReference1.IAccountingV1 {
        
        public AccountingV1Client() {
        }
        
        public AccountingV1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountingV1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountingV1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountingV1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getInvoiceServicesSumAmt() {
            return base.Channel.getInvoiceServicesSumAmt();
        }
    }
}
