//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace DocArchive.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DOCContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DOCContext object using the connection string found in the 'DOCContext' section of the application configuration file.
        /// </summary>
        public DOCContext() : base("name=DOCContext", "DOCContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DOCContext object.
        /// </summary>
        public DOCContext(string connectionString) : base(connectionString, "DOCContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DOCContext object.
        /// </summary>
        public DOCContext(EntityConnection connection) : base(connection, "DOCContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<topic> topic
        {
            get
            {
                if ((_topic == null))
                {
                    _topic = base.CreateObjectSet<topic>("topic");
                }
                return _topic;
            }
        }
        private ObjectSet<topic> _topic;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the topic EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotopic(topic topic)
        {
            base.AddObject("topic", topic);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_40114_codeclubModel", Name="topic")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class topic : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new topic object.
        /// </summary>
        /// <param name="topic_id">Initial value of the topic_id property.</param>
        public static topic Createtopic(global::System.Int32 topic_id)
        {
            topic topic = new topic();
            topic.topic_id = topic_id;
            return topic;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 topic_id
        {
            get
            {
                return _topic_id;
            }
            set
            {
                if (_topic_id != value)
                {
                    Ontopic_idChanging(value);
                    ReportPropertyChanging("topic_id");
                    _topic_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("topic_id");
                    Ontopic_idChanged();
                }
            }
        }
        private global::System.Int32 _topic_id;
        partial void Ontopic_idChanging(global::System.Int32 value);
        partial void Ontopic_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> topic_parent_id
        {
            get
            {
                return _topic_parent_id;
            }
            set
            {
                Ontopic_parent_idChanging(value);
                ReportPropertyChanging("topic_parent_id");
                _topic_parent_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("topic_parent_id");
                Ontopic_parent_idChanged();
            }
        }
        private Nullable<global::System.Int32> _topic_parent_id;
        partial void Ontopic_parent_idChanging(Nullable<global::System.Int32> value);
        partial void Ontopic_parent_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String topic_title
        {
            get
            {
                return _topic_title;
            }
            set
            {
                Ontopic_titleChanging(value);
                ReportPropertyChanging("topic_title");
                _topic_title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("topic_title");
                Ontopic_titleChanged();
            }
        }
        private global::System.String _topic_title;
        partial void Ontopic_titleChanging(global::System.String value);
        partial void Ontopic_titleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String topic_details
        {
            get
            {
                return _topic_details;
            }
            set
            {
                Ontopic_detailsChanging(value);
                ReportPropertyChanging("topic_details");
                _topic_details = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("topic_details");
                Ontopic_detailsChanged();
            }
        }
        private global::System.String _topic_details;
        partial void Ontopic_detailsChanging(global::System.String value);
        partial void Ontopic_detailsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> is_active
        {
            get
            {
                return _is_active;
            }
            set
            {
                Onis_activeChanging(value);
                ReportPropertyChanging("is_active");
                _is_active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_active");
                Onis_activeChanged();
            }
        }
        private Nullable<global::System.Boolean> _is_active;
        partial void Onis_activeChanging(Nullable<global::System.Boolean> value);
        partial void Onis_activeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String datetime
        {
            get
            {
                return _datetime;
            }
            set
            {
                OndatetimeChanging(value);
                ReportPropertyChanging("datetime");
                _datetime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("datetime");
                OndatetimeChanged();
            }
        }
        private global::System.String _datetime;
        partial void OndatetimeChanging(global::System.String value);
        partial void OndatetimeChanged();

        #endregion

    
    }

    #endregion

    
}
