//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DB_40114_codeclubModel", "Reciever", "person", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Accounting.Models.person), "Service", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Accounting.Models.Service), true)]
[assembly: EdmRelationshipAttribute("DB_40114_codeclubModel", "Sender", "person", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Accounting.Models.person), "Service", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Accounting.Models.Service), true)]

#endregion

namespace Accounting.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AccContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AccContext object using the connection string found in the 'AccContext' section of the application configuration file.
        /// </summary>
        public AccContext() : base("name=AccContext", "AccContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AccContext object.
        /// </summary>
        public AccContext(string connectionString) : base(connectionString, "AccContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AccContext object.
        /// </summary>
        public AccContext(EntityConnection connection) : base(connection, "AccContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Service> Service
        {
            get
            {
                if ((_Service == null))
                {
                    _Service = base.CreateObjectSet<Service>("Service");
                }
                return _Service;
            }
        }
        private ObjectSet<Service> _Service;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<person> person
        {
            get
            {
                if ((_person == null))
                {
                    _person = base.CreateObjectSet<person>("person");
                }
                return _person;
            }
        }
        private ObjectSet<person> _person;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Currency> Currency
        {
            get
            {
                if ((_Currency == null))
                {
                    _Currency = base.CreateObjectSet<Currency>("Currency");
                }
                return _Currency;
            }
        }
        private ObjectSet<Currency> _Currency;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CurrencyType> CurrencyType
        {
            get
            {
                if ((_CurrencyType == null))
                {
                    _CurrencyType = base.CreateObjectSet<CurrencyType>("CurrencyType");
                }
                return _CurrencyType;
            }
        }
        private ObjectSet<CurrencyType> _CurrencyType;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GLType> GLType
        {
            get
            {
                if ((_GLType == null))
                {
                    _GLType = base.CreateObjectSet<GLType>("GLType");
                }
                return _GLType;
            }
        }
        private ObjectSet<GLType> _GLType;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<invoice> invoice
        {
            get
            {
                if ((_invoice == null))
                {
                    _invoice = base.CreateObjectSet<invoice>("invoice");
                }
                return _invoice;
            }
        }
        private ObjectSet<invoice> _invoice;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CategoryType> CategoryType
        {
            get
            {
                if ((_CategoryType == null))
                {
                    _CategoryType = base.CreateObjectSet<CategoryType>("CategoryType");
                }
                return _CategoryType;
            }
        }
        private ObjectSet<CategoryType> _CategoryType;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Service EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToService(Service service)
        {
            base.AddObject("Service", service);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the person EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToperson(person person)
        {
            base.AddObject("person", person);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Currency EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCurrency(Currency currency)
        {
            base.AddObject("Currency", currency);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CurrencyType EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCurrencyType(CurrencyType currencyType)
        {
            base.AddObject("CurrencyType", currencyType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GLType EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGLType(GLType gLType)
        {
            base.AddObject("GLType", gLType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the invoice EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToinvoice(invoice invoice)
        {
            base.AddObject("invoice", invoice);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CategoryType EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategoryType(CategoryType categoryType)
        {
            base.AddObject("CategoryType", categoryType);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public int reset_GLTypeSeed()
        {
            return base.ExecuteFunction("reset_GLTypeSeed");
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_40114_codeclubModel", Name="CategoryType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CategoryType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CategoryType object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static CategoryType CreateCategoryType(global::System.Int32 id)
        {
            CategoryType categoryType = new CategoryType();
            categoryType.ID = id;
            return categoryType;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_40114_codeclubModel", Name="Currency")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Currency : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Currency object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Currency CreateCurrency(global::System.Int32 id)
        {
            Currency currency = new Currency();
            currency.ID = id;
            return currency;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> type_id
        {
            get
            {
                return _type_id;
            }
            set
            {
                Ontype_idChanging(value);
                ReportPropertyChanging("type_id");
                _type_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("type_id");
                Ontype_idChanged();
            }
        }
        private Nullable<global::System.Int32> _type_id;
        partial void Ontype_idChanging(Nullable<global::System.Int32> value);
        partial void Ontype_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_40114_codeclubModel", Name="CurrencyType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CurrencyType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CurrencyType object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static CurrencyType CreateCurrencyType(global::System.Int32 id)
        {
            CurrencyType currencyType = new CurrencyType();
            currencyType.ID = id;
            return currencyType;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_40114_codeclubModel", Name="GLType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GLType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GLType object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static GLType CreateGLType(global::System.Int32 id)
        {
            GLType gLType = new GLType();
            gLType.ID = id;
            return gLType;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_40114_codeclubModel", Name="invoice")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class invoice : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new invoice object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="receiver_id">Initial value of the receiver_id property.</param>
        /// <param name="sender_id">Initial value of the sender_id property.</param>
        /// <param name="currency_id">Initial value of the currency_id property.</param>
        /// <param name="amount">Initial value of the amount property.</param>
        /// <param name="service_id">Initial value of the service_id property.</param>
        /// <param name="timestamp">Initial value of the timestamp property.</param>
        public static invoice Createinvoice(global::System.Int32 id, global::System.Int32 receiver_id, global::System.Int32 sender_id, global::System.Int32 currency_id, global::System.Decimal amount, global::System.Int32 service_id, global::System.String timestamp)
        {
            invoice invoice = new invoice();
            invoice.ID = id;
            invoice.receiver_id = receiver_id;
            invoice.sender_id = sender_id;
            invoice.currency_id = currency_id;
            invoice.amount = amount;
            invoice.service_id = service_id;
            invoice.timestamp = timestamp;
            return invoice;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 receiver_id
        {
            get
            {
                return _receiver_id;
            }
            set
            {
                Onreceiver_idChanging(value);
                ReportPropertyChanging("receiver_id");
                _receiver_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("receiver_id");
                Onreceiver_idChanged();
            }
        }
        private global::System.Int32 _receiver_id;
        partial void Onreceiver_idChanging(global::System.Int32 value);
        partial void Onreceiver_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sender_id
        {
            get
            {
                return _sender_id;
            }
            set
            {
                Onsender_idChanging(value);
                ReportPropertyChanging("sender_id");
                _sender_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sender_id");
                Onsender_idChanged();
            }
        }
        private global::System.Int32 _sender_id;
        partial void Onsender_idChanging(global::System.Int32 value);
        partial void Onsender_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 currency_id
        {
            get
            {
                return _currency_id;
            }
            set
            {
                Oncurrency_idChanging(value);
                ReportPropertyChanging("currency_id");
                _currency_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("currency_id");
                Oncurrency_idChanged();
            }
        }
        private global::System.Int32 _currency_id;
        partial void Oncurrency_idChanging(global::System.Int32 value);
        partial void Oncurrency_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal amount
        {
            get
            {
                return _amount;
            }
            set
            {
                OnamountChanging(value);
                ReportPropertyChanging("amount");
                _amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("amount");
                OnamountChanged();
            }
        }
        private global::System.Decimal _amount;
        partial void OnamountChanging(global::System.Decimal value);
        partial void OnamountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 service_id
        {
            get
            {
                return _service_id;
            }
            set
            {
                Onservice_idChanging(value);
                ReportPropertyChanging("service_id");
                _service_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("service_id");
                Onservice_idChanged();
            }
        }
        private global::System.Int32 _service_id;
        partial void Onservice_idChanging(global::System.Int32 value);
        partial void Onservice_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String timestamp
        {
            get
            {
                return _timestamp;
            }
            set
            {
                OntimestampChanging(value);
                ReportPropertyChanging("timestamp");
                _timestamp = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("timestamp");
                OntimestampChanged();
            }
        }
        private global::System.String _timestamp;
        partial void OntimestampChanging(global::System.String value);
        partial void OntimestampChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_40114_codeclubModel", Name="person")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class person : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new person object.
        /// </summary>
        /// <param name="person_id">Initial value of the person_id property.</param>
        public static person Createperson(global::System.Int32 person_id)
        {
            person person = new person();
            person.person_id = person_id;
            return person;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 person_id
        {
            get
            {
                return _person_id;
            }
            set
            {
                if (_person_id != value)
                {
                    Onperson_idChanging(value);
                    ReportPropertyChanging("person_id");
                    _person_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("person_id");
                    Onperson_idChanged();
                }
            }
        }
        private global::System.Int32 _person_id;
        partial void Onperson_idChanging(global::System.Int32 value);
        partial void Onperson_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fname
        {
            get
            {
                return _fname;
            }
            set
            {
                OnfnameChanging(value);
                ReportPropertyChanging("fname");
                _fname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("fname");
                OnfnameChanged();
            }
        }
        private global::System.String _fname;
        partial void OnfnameChanging(global::System.String value);
        partial void OnfnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lname
        {
            get
            {
                return _lname;
            }
            set
            {
                OnlnameChanging(value);
                ReportPropertyChanging("lname");
                _lname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lname");
                OnlnameChanged();
            }
        }
        private global::System.String _lname;
        partial void OnlnameChanging(global::System.String value);
        partial void OnlnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String thumbnailFile
        {
            get
            {
                return _thumbnailFile;
            }
            set
            {
                OnthumbnailFileChanging(value);
                ReportPropertyChanging("thumbnailFile");
                _thumbnailFile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("thumbnailFile");
                OnthumbnailFileChanged();
            }
        }
        private global::System.String _thumbnailFile;
        partial void OnthumbnailFileChanging(global::System.String value);
        partial void OnthumbnailFileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String thumbnailExt
        {
            get
            {
                return _thumbnailExt;
            }
            set
            {
                OnthumbnailExtChanging(value);
                ReportPropertyChanging("thumbnailExt");
                _thumbnailExt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("thumbnailExt");
                OnthumbnailExtChanged();
            }
        }
        private global::System.String _thumbnailExt;
        partial void OnthumbnailExtChanging(global::System.String value);
        partial void OnthumbnailExtChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_40114_codeclubModel", "Reciever", "Service")]
        public EntityCollection<Service> Service
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Service>("DB_40114_codeclubModel.Reciever", "Service");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Service>("DB_40114_codeclubModel.Reciever", "Service", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_40114_codeclubModel", "Sender", "Service")]
        public EntityCollection<Service> Service1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Service>("DB_40114_codeclubModel.Sender", "Service");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Service>("DB_40114_codeclubModel.Sender", "Service", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_40114_codeclubModel", Name="Service")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Service : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Service object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Service CreateService(global::System.Int32 id)
        {
            Service service = new Service();
            service.ID = id;
            return service;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> senderId
        {
            get
            {
                return _senderId;
            }
            set
            {
                OnsenderIdChanging(value);
                ReportPropertyChanging("senderId");
                _senderId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("senderId");
                OnsenderIdChanged();
            }
        }
        private Nullable<global::System.Int32> _senderId;
        partial void OnsenderIdChanging(Nullable<global::System.Int32> value);
        partial void OnsenderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> receiverId
        {
            get
            {
                return _receiverId;
            }
            set
            {
                OnreceiverIdChanging(value);
                ReportPropertyChanging("receiverId");
                _receiverId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("receiverId");
                OnreceiverIdChanged();
            }
        }
        private Nullable<global::System.Int32> _receiverId;
        partial void OnreceiverIdChanging(Nullable<global::System.Int32> value);
        partial void OnreceiverIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String serviceName
        {
            get
            {
                return _serviceName;
            }
            set
            {
                OnserviceNameChanging(value);
                ReportPropertyChanging("serviceName");
                _serviceName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("serviceName");
                OnserviceNameChanged();
            }
        }
        private global::System.String _serviceName;
        partial void OnserviceNameChanging(global::System.String value);
        partial void OnserviceNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_40114_codeclubModel", "Reciever", "person")]
        public person person
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<person>("DB_40114_codeclubModel.Reciever", "person").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<person>("DB_40114_codeclubModel.Reciever", "person").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<person> personReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<person>("DB_40114_codeclubModel.Reciever", "person");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<person>("DB_40114_codeclubModel.Reciever", "person", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_40114_codeclubModel", "Sender", "person")]
        public person person1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<person>("DB_40114_codeclubModel.Sender", "person").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<person>("DB_40114_codeclubModel.Sender", "person").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<person> person1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<person>("DB_40114_codeclubModel.Sender", "person");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<person>("DB_40114_codeclubModel.Sender", "person", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
