var data = { description: "Chief Executive Officer (CEO)",
	email: "davidalt@name.com",
	groupTitleColor: "#4169e1",
	image: "q.png",
	itemTitleColor: "#4169e1",
	items: [ { description: "Co-Presidents, Platform Products & Services Division",
		email: "jeanwhit@name.com",
		groupTitleColor: "#4169e1",
		image: "w.png",
		itemTitleColor: "#4b0082",
		items: [ { description: "Sr. VP, Server & Tools Division",
			email: "jameholt@name.com",
			groupTitleColor: "#4169e1",
			image: "e.png",
			itemTitleColor: "#4b0082",
			items: [ { description: "VP, Server & Tools Marketing and Solutions",
				email: "thomwill@name.com",
				groupTitleColor: "#4169e1",
				image: "r.png",
				itemTitleColor: "#4b0082",
				items: [ { description: "GM, Infrastructure Server and IT Pro Audience Marketing",
					email: "davikirb@name.com",
					groupTitleColor: "#4169e1",
					image: "t.png",
					itemTitleColor: "#4b0082",
					phone: "614-395-7238",
					title: "David Kirby"
				},
						{ description: "GM, Name.com Experience Platforms and Solutions",
							email: "lynemalo@name.com",
							groupTitleColor: "#4169e1",
							image: "y.png",
							itemTitleColor: "#4b0082",
							items: [ { description: "GM, Core Infrastructure Solutions",
								email: "glenzeig@name.com",
								groupTitleColor: "#4169e1",
								image: "u.png",
								itemTitleColor: "#4b0082",
								phone: "920-665-7222",
								title: "Glen Zeigler"
							},
									{ description: "GM, Patterns & Practices",
										email: "ionegall@name.com",
										groupTitleColor: "#4169e1",
										image: "i.png",
										itemTitleColor: "#4b0082",
										phone: "478-322-5539",
										title: "Ione Gallegos"
									},
									{ description: "GM, TechNet and MSDN",
										email: "joseclar@name.com",
										groupTitleColor: "#4169e1",
										image: "o.png",
										itemTitleColor: "#4b0082",
										phone: "401-218-3019",
										title: "Jose Clark"
									}
							],
							phone: "540-822-3862",
							title: "Lynette Maloney"
						},
						{ description: "GM, Name Learning",
							email: "heatsimm@name.com",
							groupTitleColor: "#4169e1",
							image: "p.png",
							itemTitleColor: "#4b0082",
							phone: "620-368-3620",
							title: "Heather Simmons"
						},
						{ description: "GM, Platform Strategy",
							email: "stevlaco@name.com",
							groupTitleColor: "#4169e1",
							image: "a.png",
							itemTitleColor: "#4b0082",
							items: [ { description: "GM, Strategic Marketing and Communications",
								email: "nancsmit@name.com",
								groupTitleColor: "#4169e1",
								image: "s.png",
								itemTitleColor: "#4b0082",
								phone: "631-787-3495",
								title: "Nancy Smith"
							} ],
							phone: "805-800-7397",
							title: "Steven Lacombe"
						},
						{ description: "GM, DML Server Marketing",
							email: "jeankend@name.com",
							groupTitleColor: "#4169e1",
							image: "d.png",
							itemTitleColor: "#4b0082",
							phone: "949-453-0415",
							title: "Jean Kendall"
						},
						{ description: "GM, Application Platform and Development Marketing",
							email: "bradwhit@name.com",
							groupTitleColor: "#4169e1",
							image: "f.png",
							itemTitleColor: "#4b0082",
							phone: "502-528-6379",
							title: "Brad Whitt"
						}
				],
				phone: "904-547-5342",
				title: "Thomas Williams"
			},
					{ description: "VP, Software & Enterprise Management Division",
						email: "sarakemp@name.com",
						groupTitleColor: "#4169e1",
						image: "g.png",
						itemTitleColor: "#4b0082",
						items: [ { description: "GM, Systems Management Server",
							email: "briacruz@name.com",
							groupTitleColor: "#4169e1",
							image: "h.png",
							itemTitleColor: "#4b0082",
							phone: "320-833-9024",
							title: "Brian Cruz"
						},
								{ description: "GM, Software Management",
									email: "johndrak@name.com",
									groupTitleColor: "#4169e1",
									image: "j.png",
									itemTitleColor: "#4b0082",
									phone: "469-644-8543",
									title: "John Drake"
								},
								{ description: "GM, Storage Platforms & Solutions",
									email: "patrperr@name.com",
									groupTitleColor: "#4169e1",
									image: "k.png",
									itemTitleColor: "#4b0082",
									phone: "781-515-5949",
									title: "Patrick Perry"
								},
								{ description: "GM, Manageability and Deployment",
									email: "maryspen@name.com",
									groupTitleColor: "#4169e1",
									image: "l.png",
									itemTitleColor: "#4b0082",
									phone: "605-892-8662",
									title: "Mary Spencer"
								},
								{ description: "GM, Operations Manager",
									email: "thomdixo@name.com",
									groupTitleColor: "#4169e1",
									image: "z.png",
									itemTitleColor: "#4b0082",
									phone: "651-249-4047",
									title: "Thomas Dixon"
								}
						],
						phone: "918-257-4218",
						title: "Sara Kemp"
					},
					{ description: "Sr. VP, Software Server System",
						email: "georduon@name.com",
						groupTitleColor: "#4169e1",
						image: "x.png",
						itemTitleColor: "#4b0082",
						items: [ { description: "GM, DML Server Strategy",
							email: "ralpmerc@name.com",
							groupTitleColor: "#4169e1",
							image: "c.png",
							itemTitleColor: "#4b0082",
							phone: "814-327-5895",
							title: "Ralph Mercer"
						},
								{ description: "GM, User Experience",
									email: "howawill@name.com",
									groupTitleColor: "#4169e1",
									image: "v.png",
									itemTitleColor: "#4b0082",
									phone: "703-740-8612",
									title: "Howard Williams"
								},
								{ description: "GM, DML Server Business Intelligence",
									email: "nathesco@name.com",
									groupTitleColor: "#4169e1",
									image: "b.png",
									itemTitleColor: "#4b0082",
									phone: "504-555-8165",
									title: "Nathalie Escobedo"
								}
						],
						phone: "434-406-2189",
						title: "George Duong"
					},
					{ description: "VP, Developer Division",
						email: "ashlrue@name.com",
						groupTitleColor: "#4169e1",
						image: "n.png",
						itemTitleColor: "#4b0082",
						items: [ { description: "VP, .ORG Developer Platform Team",
							email: "joanwhit@name.com",
							groupTitleColor: "#4169e1",
							image: "m.png",
							itemTitleColor: "#4b0082",
							items: [ { description: "GM, Web and UI Development Platform",
								email: "janecann@name.com",
								groupTitleColor: "#4169e1",
								image: "q.png",
								itemTitleColor: "#4b0082",
								phone: "484-870-9064",
								title: "Janella Cannon"
							} ],
							phone: "914-614-5020",
							title: "Joan Whitham"
						},
								{ description: "GM, Visual Studio",
									email: "rogegree@name.com",
									groupTitleColor: "#4169e1",
									image: "w.png",
									itemTitleColor: "#4b0082",
									items: [ { description: "GM, Office System and Applications Developer Tools",
										email: "ednagarn@name.com",
										groupTitleColor: "#4169e1",
										image: "e.png",
										itemTitleColor: "#4b0082",
										phone: "620-873-1915",
										title: "Edna Garner"
									},
											{ description: "GM, Visual Studio Team System",
												email: "brenhols@name.com",
												groupTitleColor: "#4169e1",
												image: "r.png",
												itemTitleColor: "#4b0082",
												phone: "925-386-2127",
												title: "Brent Holston"
											},
											{ description: "GM, Visual Studio Language and Data Tools",
												email: "maryruss@name.com",
												groupTitleColor: "#4169e1",
												image: "t.png",
												itemTitleColor: "#4b0082",
												phone: "443-271-9086",
												title: "Mary Russ"
											}
									],
									phone: "847-510-2148",
									title: "Roger Greenlee"
								},
								{ description: "Managing Dir., India Development Center",
									email: "stanweat@name.com",
									groupTitleColor: "#4169e1",
									image: "y.png",
									itemTitleColor: "#4b0082",
									items: [ { description: "GM, Real Time Collaboration & Home Entertainment Products",
										email: "melvwhit@name.com",
										groupTitleColor: "#4169e1",
										image: "u.png",
										itemTitleColor: "#4b0082",
										phone: "785-631-8548",
										title: "Melvin White"
									} ],
									phone: "734-482-1633",
									title: "Stanley Weathers"
								}
						],
						phone: "515-324-4969",
						title: "Ashley Rue"
					},
					{ description: "VP, Enterprise Access and Security Products Division (EASP)",
						email: "bonnwede@name.com",
						groupTitleColor: "#4169e1",
						image: "i.png",
						itemTitleColor: "#4b0082",
						items: [ { description: "GM, Haifa R&D Center",
							email: "normdalt@name.com",
							groupTitleColor: "#4169e1",
							image: "o.png",
							itemTitleColor: "#4b0082",
							phone: "316-334-6273",
							title: "Norman Dalton"
						} ],
						phone: "412-265-2782",
						title: "Bonnie Wedel"
					},
					{ description: "GM, Core File Solutions",
						email: "melihous@name.com",
						groupTitleColor: "#4169e1",
						image: "p.png",
						itemTitleColor: "#4b0082",
						phone: "630-887-1188",
						title: "Melissa Houser"
					},
					{ description: "GM, Software Server Solutions Group",
						email: "abbilaws@name.com",
						groupTitleColor: "#4169e1",
						image: "a.png",
						itemTitleColor: "#4b0082",
						phone: "530-322-6413",
						title: "Abbie Lawson"
					},
					{ description: "GM, Connected Systems Division",
						email: "erneputn@name.com",
						groupTitleColor: "#4169e1",
						image: "s.png",
						itemTitleColor: "#4b0082",
						items: [ { description: "GM, Connected Framework",
							email: "robelemi@name.com",
							groupTitleColor: "#4169e1",
							image: "d.png",
							itemTitleColor: "#4b0082",
							phone: "662-787-2600",
							title: "Robert Lemieux"
						},
								{ description: "GM, XML Enterprise Services",
									email: "arthwood@name.com",
									groupTitleColor: "#4169e1",
									image: "f.png",
									itemTitleColor: "#4b0082",
									phone: "630-677-5265",
									title: "Arthur Wood"
								},
								{ description: "GM, BizTalk Server",
									email: "jonahitt@name.com",
									groupTitleColor: "#4169e1",
									image: "g.png",
									itemTitleColor: "#4b0082",
									phone: "443-591-0659",
									title: "Jonathan Hitt"
								}
						],
						phone: "626-831-0555",
						title: "Ernest Putnam"
					}
			],
			phone: "262-215-7998",
			title: "James Holt"
		},
				{ description: "CFO, Platforms Products & Services",
					email: "celecrum@name.com",
					groupTitleColor: "#4169e1",
					image: "h.png",
					itemTitleColor: "#4b0082",
					items: [ { description: "GM, Pricing",
						email: "cindturn@name.com",
						groupTitleColor: "#4169e1",
						image: "j.png",
						itemTitleColor: "#4b0082",
						phone: "530-934-4295",
						title: "Cindy Turner"
					},
							{ description: "GM, Worldwide Licensing",
								email: "victsequ@name.com",
								groupTitleColor: "#4169e1",
								image: "k.png",
								itemTitleColor: "#4b0082",
								items: [ { description: "GM, Name Financing",
									email: "jamework@name.com",
									groupTitleColor: "#4169e1",
									image: "l.png",
									itemTitleColor: "#4b0082",
									phone: "713-624-6200",
									title: "James Workman"
								},
										{ description: "GM, WW Licensing Programs",
											email: "giladam@name.com",
											groupTitleColor: "#4169e1",
											image: "z.png",
											itemTitleColor: "#4b0082",
											phone: "313-630-8717",
											title: "Gil Adams"
										}
								],
								phone: "973-883-9137",
								title: "Victoria Sequeira"
							},
							{ description: "GM, WW Licensing Solutions",
								email: "normmoor@name.com",
								groupTitleColor: "#4169e1",
								image: "x.png",
								itemTitleColor: "#4b0082",
								phone: "334-496-5203",
								title: "Norma Moore"
							},
							{ description: "GM, Marketing and Readiness",
								email: "carlcard@name.com",
								groupTitleColor: "#4169e1",
								image: "c.png",
								itemTitleColor: "#4b0082",
								phone: "775-999-3630",
								title: "Carlos Cardenas"
							}
					],
					phone: "419-578-6479",
					title: "Celestina Crum"
				},
				{ description: "Sr. VP, Software Core Operating System Division",
					email: "johngree@name.com",
					groupTitleColor: "#4169e1",
					image: "v.png",
					itemTitleColor: "#4b0082",
					items: [ { description: "VP, Core OS Development",
						email: "richmora@name.com",
						groupTitleColor: "#4169e1",
						image: "b.png",
						itemTitleColor: "#4b0082",
						items: [ { description: "VP, Software Architecture and Kernel",
							email: "carojone@name.com",
							groupTitleColor: "#4169e1",
							image: "n.png",
							itemTitleColor: "#4b0082",
							phone: "903-859-0477",
							title: "Carolyn Jones"
						} ],
						phone: "650-729-6483",
						title: "Richard Morales"
					},
							{ description: "VP, Software Networking & Device Technologies",
								email: "charwhit@name.com",
								groupTitleColor: "#4169e1",
								image: "m.png",
								itemTitleColor: "#4b0082",
								items: [ { description: "GM, Software Device Experience Group",
									email: "elizzito@name.com",
									groupTitleColor: "#4169e1",
									image: "q.png",
									itemTitleColor: "#4b0082",
									items: [ { description: "GM, Software Device Experience",
										email: "ednacava@name.com",
										groupTitleColor: "#4169e1",
										image: "w.png",
										itemTitleColor: "#4b0082",
										phone: "337-977-6357",
										title: "Edna Cavazos"
									} ],
									phone: "307-201-4036",
									title: "Elizabeth Zito"
								},
										{ description: "GM, Core Networking and Collaboration",
											email: "debrmaye@name.com",
											groupTitleColor: "#4169e1",
											image: "e.png",
											itemTitleColor: "#4b0082",
											phone: "334-538-2338",
											title: "Debra Mayers"
										},
										{ description: "GM, Cableless & Mobility",
											email: "geracast@name.com",
											groupTitleColor: "#4169e1",
											image: "r.png",
											itemTitleColor: "#4b0082",
											phone: "706-541-8969",
											title: "Gerald Castonguay"
										},
										{ description: "GM, Network Infrastructure Servers",
											email: "kevicari@name.com",
											groupTitleColor: "#4169e1",
											image: "t.png",
											itemTitleColor: "#4b0082",
											phone: "530-452-7085",
											title: "Kevin Carico"
										}
								],
								phone: "248-402-6142",
								title: "Charlotte White"
							},
							{ description: "VP, Security Technology Unit (STU)",
								email: "robemorg@name.com",
								groupTitleColor: "#4169e1",
								image: "y.png",
								itemTitleColor: "#4b0082",
								items: [ { description: "VP",
									email: "susahain@name.com",
									groupTitleColor: "#4169e1",
									image: "u.png",
									itemTitleColor: "#4b0082",
									phone: "937-738-0077",
									title: "Susan Haines"
								},
										{ description: "GM, Software Security",
											email: "jameperr@name.com",
											groupTitleColor: "#4169e1",
											image: "i.png",
											itemTitleColor: "#4b0082",
											items: [ { description: "GM, Software Security Access Control",
												email: "edwiking@name.com",
												groupTitleColor: "#4169e1",
												image: "o.png",
												itemTitleColor: "#4b0082",
												phone: "386-767-9910",
												title: "Edwin King"
											} ],
											phone: "914-545-0715",
											title: "James Perry"
										},
										{ description: "GM, System Protection Technologies",
											email: "juansmit@name.com",
											groupTitleColor: "#4169e1",
											image: "p.png",
											itemTitleColor: "#4b0082",
											phone: "360-519-7051",
											title: "Juan Smith"
										}
								],
								phone: "308-532-6548",
								title: "Robert Morgan"
							},
							{ description: "GM, Software Serviceability",
								email: "idabene@name.com",
								groupTitleColor: "#4169e1",
								image: "a.png",
								itemTitleColor: "#4b0082",
								items: [ { description: "GM, Engineering Serviceability",
									email: "andrhall@name.com",
									groupTitleColor: "#4169e1",
									image: "s.png",
									itemTitleColor: "#4b0082",
									phone: "863-307-4799",
									title: "Andrew Hall"
								} ],
								phone: "765-723-1327",
								title: "Ida Benefield"
							},
							{ description: "GM, Core Operating System Test",
								email: "vadaduho@name.com",
								groupTitleColor: "#4169e1",
								image: "d.png",
								itemTitleColor: "#4b0082",
								phone: "303-333-9215",
								title: "Vada Duhon"
							},
							{ description: "GM, Global Platform Technologies and Services",
								email: "willloyd@name.com",
								groupTitleColor: "#4169e1",
								image: "f.png",
								itemTitleColor: "#4b0082",
								phone: "585-309-6253",
								title: "William Loyd"
							}
					],
					phone: "937-475-8106",
					title: "John Green"
				},
				{ description: "Sr. VP, NAME & Personal Services Division",
					email: "craiblue@name.com",
					groupTitleColor: "#4169e1",
					image: "g.png",
					itemTitleColor: "#4b0082",
					items: [ { description: "VP, NAME Communications Services and Member Platform",
						email: "joelcraw@name.com",
						groupTitleColor: "#4169e1",
						image: "h.png",
						itemTitleColor: "#4b0082",
						items: [ { description: "VP, NAME Communication Services Platform",
							email: "astrcamp@name.com",
							groupTitleColor: "#4169e1",
							image: "j.png",
							itemTitleColor: "#4b0082",
							items: [ { description: "GM, NAME Mobile",
								email: "johnpeyt@name.com",
								groupTitleColor: "#4169e1",
								image: "k.png",
								itemTitleColor: "#4b0082",
								phone: "321-453-9485",
								title: "John Peyton"
							},
									{ description: "GM, NAME Communication Services Platform",
										email: "tonyross@name.com",
										groupTitleColor: "#4169e1",
										image: "l.png",
										itemTitleColor: "#4b0082",
										phone: "916-962-1004",
										title: "Tony Ross"
									}
							],
							phone: "630-823-2026",
							title: "Astrid Camp"
						},
								{ description: "VP, Software Live User Experience",
									email: "lindmors@name.com",
									groupTitleColor: "#4169e1",
									image: "z.png",
									itemTitleColor: "#4b0082",
									items: [ { description: "GM, Communication Clients",
										email: "timobroo@name.com",
										groupTitleColor: "#4169e1",
										image: "x.png",
										itemTitleColor: "#4b0082",
										phone: "870-560-2206",
										title: "Timothy Brooks"
									},
											{ description: "GM, Web Experience",
												email: "maryklin@name.com",
												groupTitleColor: "#4169e1",
												image: "c.png",
												itemTitleColor: "#4b0082",
												phone: "443-538-3451",
												title: "Mary Klingler"
											},
											{ description: "GM, Member Experience",
												email: "jamegunt@name.com",
												groupTitleColor: "#4169e1",
												image: "v.png",
												itemTitleColor: "#4b0082",
												phone: "732-659-8265",
												title: "James Gunther"
											}
									],
									phone: "617-555-2961",
									title: "Linda Morse"
								},
								{ description: "GM, Product Management",
									email: "franhatc@name.com",
									groupTitleColor: "#4169e1",
									image: "b.png",
									itemTitleColor: "#4b0082",
									items: [ { description: "GM, Online Safety & Security",
										email: "barbshad@name.com",
										groupTitleColor: "#4169e1",
										image: "n.png",
										itemTitleColor: "#4b0082",
										phone: "906-622-7369",
										title: "Barbie Shadle"
									},
											{ description: "GM, NAME & Software Live Global Consumer Marketing",
												email: "heatcolo@name.com",
												groupTitleColor: "#4169e1",
												image: "m.png",
												itemTitleColor: "#4b0082",
												phone: "352-266-5067",
												title: "Heather Colon"
											}
									],
									phone: "925-570-1293",
									title: "Francine Hatch"
								},
								{ description: "GM, Member Platform Group",
									email: "marxtobi@name.com",
									groupTitleColor: "#4169e1",
									image: "q.png",
									itemTitleColor: "#4b0082",
									phone: "417-766-2737",
									title: "Marx Tobin"
								},
								{ description: "GM, NAME Worldwide Product Development.",
									email: "vickmay@name.com",
									groupTitleColor: "#4169e1",
									image: "w.png",
									itemTitleColor: "#4b0082",
									phone: "262-869-4968",
									title: "Vickie May"
								},
								{ description: "Chief of Staff, NAME Communications Services and Membership Platform",
									email: "andrhort@name.com",
									groupTitleColor: "#4169e1",
									image: "e.png",
									itemTitleColor: "#4b0082",
									phone: "630-431-1872",
									title: "Andrew Horton"
								},
								{ description: "GM, CS&MP Business Development",
									email: "glennumb@name.com",
									groupTitleColor: "#4169e1",
									image: "r.png",
									itemTitleColor: "#4b0082",
									phone: "512-907-7754",
									title: "Glenn Numbers"
								},
								{ description: "GM, Technology Care and Safety Group",
									email: "deancald@name.com",
									groupTitleColor: "#4169e1",
									image: "t.png",
									itemTitleColor: "#4b0082",
									items: [ { description: "GM, Anti-Spam & Phishing",
										email: "louhoff@name.com",
										groupTitleColor: "#4169e1",
										image: "y.png",
										itemTitleColor: "#4b0082",
										phone: "757-382-9554",
										title: "Lou Hoffman"
									},
											{ description: "GM, Personal Safety",
												email: "barbroge@name.com",
												groupTitleColor: "#4169e1",
												image: "u.png",
												itemTitleColor: "#4b0082",
												phone: "310-783-8039",
												title: "Barbara Rogers"
											},
											{ description: "GM, Software OneCare Live",
												email: "annimurp@name.com",
												groupTitleColor: "#4169e1",
												image: "i.png",
												itemTitleColor: "#4b0082",
												phone: "732-936-1233",
												title: "Annie Murphy"
											}
									],
									phone: "254-423-1179",
									title: "Deanna Caldwell"
								}
						],
						phone: "650-623-3302",
						title: "Joel Crawford"
					},
							{ description: "VP & CFO, NAME",
								email: "barblang@name.com",
								groupTitleColor: "#4169e1",
								image: "o.png",
								itemTitleColor: "#4b0082",
								items: [ { description: "GM., NAME Strategy",
									email: "donnreil@name.com",
									groupTitleColor: "#4169e1",
									image: "p.png",
									itemTitleColor: "#4b0082",
									phone: "256-778-6929",
									title: "Donna Reilly"
								},
										{ description: "GM, NAME Business Development & Partnerships",
											email: "jenieddy@name.com",
											groupTitleColor: "#4169e1",
											image: "a.png",
											itemTitleColor: "#4b0082",
											items: [ { description: "GM, NAME Business Development",
												email: "willweye@name.com",
												groupTitleColor: "#4169e1",
												image: "s.png",
												itemTitleColor: "#4b0082",
												phone: "321-695-8205",
												title: "William Weyer"
											} ],
											phone: "252-798-8457",
											title: "Jenifer Eddy"
										}
								],
								phone: "618-822-7345",
								title: "Barbara Lang"
							},
							{ description: "VP, NAME Operations",
								email: "barbfaul@name.com",
								groupTitleColor: "#4169e1",
								image: "d.png",
								itemTitleColor: "#4b0082",
								items: [ { description: "GM, Infrastructure Services",
									email: "georo'co@name.com",
									groupTitleColor: "#4169e1",
									image: "f.png",
									itemTitleColor: "#4b0082",
									phone: "252-344-0685",
									title: "George O'Connor"
								},
										{ description: "GM, Chief Information Security Officer",
											email: "stepgodb@name.com",
											groupTitleColor: "#4169e1",
											image: "g.png",
											itemTitleColor: "#4b0082",
											phone: "586-339-0888",
											title: "Stephanie Godbey"
										},
										{ description: "GM, NAME Operations",
											email: "willrink@name.com",
											groupTitleColor: "#4169e1",
											image: "h.png",
											itemTitleColor: "#4b0082",
											items: [ { description: "GM, NAME Service Quality",
												email: "lisaclem@name.com",
												groupTitleColor: "#4169e1",
												image: "j.png",
												itemTitleColor: "#4b0082",
												phone: "816-561-9058",
												title: "Lisabeth Clement"
											} ],
											phone: "301-613-2003",
											title: "Willie Rinker"
										},
										{ description: "GM, NAME Customer Advocacy",
											email: "martslad@name.com",
											groupTitleColor: "#4169e1",
											image: "k.png",
											itemTitleColor: "#4b0082",
											phone: "760-799-5465",
											title: "Martha Slade"
										},
										{ description: "GM, Global Service Operations",
											email: "dororitt@name.com",
											groupTitleColor: "#4169e1",
											image: "l.png",
											itemTitleColor: "#4b0082",
											phone: "816-478-9636",
											title: "Dorothy Ritter"
										}
								],
								phone: "641-678-7646",
								title: "Barbara Faulk"
							},
							{ description: "VP, NAME Global Sales & Marketing",
								email: "stewwill@name.com",
								groupTitleColor: "#4169e1",
								image: "z.png",
								itemTitleColor: "#4b0082",
								items: [ { description: "VP, NAME Global Sales & Marketing",
									email: "montheck@name.com",
									groupTitleColor: "#4169e1",
									image: "x.png",
									itemTitleColor: "#4b0082",
									phone: "602-561-8248",
									title: "Monty Heckman"
								},
										{ description: "GM, Digital Sales & Marketing",
											email: "richsali@name.com",
											groupTitleColor: "#4169e1",
											image: "c.png",
											itemTitleColor: "#4b0082",
											phone: "917-619-4195",
											title: "Richard Salinas"
										},
										{ description: "GM, EMEA Region",
											email: "crysbett@name.com",
											groupTitleColor: "#4169e1",
											image: "v.png",
											itemTitleColor: "#4b0082",
											items: [ { description: "GM, NAME Northern Europe",
												email: "bethmcin@name.com",
												groupTitleColor: "#4169e1",
												image: "b.png",
												itemTitleColor: "#4b0082",
												phone: "713-664-0962",
												title: "Beth McInerney"
											} ],
											phone: "661-384-6406",
											title: "Crystal Betts"
										},
										{ description: "GM, Intercontinental",
											email: "calvkhan@name.com",
											groupTitleColor: "#4169e1",
											image: "n.png",
											itemTitleColor: "#4b0082",
											items: [ { description: "Reg. Dir., Pacific & Korea",
												email: "philsmit@name.com",
												groupTitleColor: "#4169e1",
												image: "m.png",
												itemTitleColor: "#4b0082",
												phone: "281-553-7458",
												title: "Phillip Smith"
											},
													{ description: "Managing. Dir., Intercontinental",
														email: "jeffruiz@name.com",
														groupTitleColor: "#4169e1",
														image: "q.png",
														itemTitleColor: "#4b0082",
														phone: "916-561-0273",
														title: "Jeffrey Ruiz"
													},
													{ description: "GM, NAME Canada",
														email: "lloyfish@name.com",
														groupTitleColor: "#4169e1",
														image: "w.png",
														itemTitleColor: "#4b0082",
														phone: "832-204-4661",
														title: "Lloyd Fisher"
													},
													{ description: "Reg. Dir., Latin America",
														email: "keviwhee@name.com",
														groupTitleColor: "#4169e1",
														image: "e.png",
														itemTitleColor: "#4b0082",
														items: [ { description: "GM, NAME",
															email: "virgfox@name.com",
															groupTitleColor: "#4169e1",
															image: "r.png",
															itemTitleColor: "#4b0082",
															phone: "716-857-4998",
															title: "Virginia Fox"
														} ],
														phone: "208-714-2419",
														title: "Kevin Wheeler"
													}
											],
											phone: "805-205-9989",
											title: "Calvin Khan"
										},
										{ description: "GM, Japan",
											email: "bettesqu@name.com",
											groupTitleColor: "#4169e1",
											image: "t.png",
											itemTitleColor: "#4b0082",
											phone: "916-468-0205",
											title: "Betty Esquivel"
										}
								],
								phone: "803-746-8733",
								title: "Stewart Williams"
							},
							{ description: "Sr. VP, NAME Information Services & Merchant Platform",
								email: "robelemi@name.com",
								groupTitleColor: "#4169e1",
								image: "y.png",
								itemTitleColor: "#4b0082",
								items: [ { description: "VP, NAME Search",
									email: "jerrskin@name.com",
									groupTitleColor: "#4169e1",
									image: "u.png",
									itemTitleColor: "#4b0082",
									items: [ { description: "GM, NAME Search",
										email: "josemack@name.com",
										groupTitleColor: "#4169e1",
										image: "i.png",
										itemTitleColor: "#4b0082",
										phone: "925-914-8213",
										title: "Jose Mack"
									},
											{ description: "GM, Local",
												email: "michwood@name.com",
												groupTitleColor: "#4169e1",
												image: "o.png",
												itemTitleColor: "#4b0082",
												items: [ { description: "GM, Local Search and Information Services",
													email: "georbjor@name.com",
													groupTitleColor: "#4169e1",
													image: "p.png",
													itemTitleColor: "#4b0082",
													phone: "618-356-2335",
													title: "George Bjorklund"
												},
														{ description: "GM, GeoPoint Business Unit and NAME Real Earth",
															email: "louismit@name.com",
															groupTitleColor: "#4169e1",
															image: "a.png",
															itemTitleColor: "#4b0082",
															phone: "650-669-5504",
															title: "Louis Smith"
														}
												],
												phone: "503-772-2763",
												title: "Michael Wood"
											},
											{ description: "GM, NAME Search Development",
												email: "horaoter@name.com",
												groupTitleColor: "#4169e1",
												image: "s.png",
												itemTitleColor: "#4b0082",
												phone: "616-230-7209",
												title: "Horace Otero"
											}
									],
									phone: "413-743-9925",
									title: "Jerry Skinner"
								},
										{ description: "GM, Client Service Operations",
											email: "ninachi@name.com",
											groupTitleColor: "#4169e1",
											image: "d.png",
											itemTitleColor: "#4b0082",
											phone: "314-629-1077",
											title: "Nina Chi"
										},
										{ description: "GM, NAME Search",
											email: "andrwilk@name.com",
											groupTitleColor: "#4169e1",
											image: "f.png",
											itemTitleColor: "#4b0082",
											phone: "703-863-7902",
											title: "Andrew Wilkerson"
										},
										{ description: "Technical Fellow, NAME",
											email: "andrwhee@name.com",
											groupTitleColor: "#4169e1",
											image: "g.png",
											itemTitleColor: "#4b0082",
											items: [ { description: "GM, Engineering",
												email: "maderedu@name.com",
												groupTitleColor: "#4169e1",
												image: "h.png",
												itemTitleColor: "#4b0082",
												phone: "704-331-8502",
												title: "Madeline Redus"
											},
													{ description: "GM, Search Labs",
														email: "victpetr@name.com",
														groupTitleColor: "#4169e1",
														image: "j.png",
														itemTitleColor: "#4b0082",
														phone: "512-468-0730",
														title: "Victor Petrie"
													}
											],
											phone: "843-200-5723",
											title: "Andrew Wheeler"
										},
										{ description: "GM, The NAME Media Network",
											email: "arlemuel@name.com",
											groupTitleColor: "#4169e1",
											image: "k.png",
											itemTitleColor: "#4b0082",
											items: [ { description: "GM, NAME.com Portal",
												email: "willblum@name.com",
												groupTitleColor: "#4169e1",
												image: "l.png",
												itemTitleColor: "#4b0082",
												phone: "208-464-5323",
												title: "William Blum"
											},
													{ description: "GM, NAME.com International",
														email: "wilbphil@name.com",
														groupTitleColor: "#4169e1",
														image: "z.png",
														itemTitleColor: "#4b0082",
														phone: "303-859-8339",
														title: "Wilbert Phillips"
													},
													{ description: "President, NAMEBC.com",
														email: "franstei@name.com",
														groupTitleColor: "#4169e1",
														image: "x.png",
														itemTitleColor: "#4b0082",
														phone: "478-719-7756",
														title: "Frances Steil"
													},
													{ description: "GM, NAME TV",
														email: "maricorr@name.com",
														groupTitleColor: "#4169e1",
														image: "c.png",
														itemTitleColor: "#4b0082",
														phone: "231-424-1059",
														title: "Maria Corrado"
													},
													{ description: "GM, Search Engine Optimization and Monetization",
														email: "eveltoom@name.com",
														groupTitleColor: "#4169e1",
														image: "v.png",
														itemTitleColor: "#4b0082",
														phone: "612-924-3953",
														title: "Evelyn Toomey"
													},
													{ description: "GM, Entertainment",
														email: "garypero@name.com",
														groupTitleColor: "#4169e1",
														image: "b.png",
														itemTitleColor: "#4b0082",
														phone: "813-737-5394",
														title: "Gary Pero"
													},
													{ description: "GM, Autos",
														email: "carlwill@name.com",
														groupTitleColor: "#4169e1",
														image: "n.png",
														itemTitleColor: "#4b0082",
														phone: "812-825-5278",
														title: "Carlos Williams"
													},
													{ description: "GM, Content Management",
														email: "danifull@name.com",
														groupTitleColor: "#4169e1",
														image: "m.png",
														itemTitleColor: "#4b0082",
														phone: "808-534-4447",
														title: "Daniel Fuller"
													},
													{ description: "GM, NAME News & Information",
														email: "jeffgree@name.com",
														groupTitleColor: "#4169e1",
														image: "q.png",
														itemTitleColor: "#4b0082",
														phone: "248-271-0572",
														title: "Jeffery Green"
													},
													{ description: "GM, Money",
														email: "natamede@name.com",
														groupTitleColor: "#4169e1",
														image: "w.png",
														itemTitleColor: "#4b0082",
														phone: "678-987-0830",
														title: "Natalie Medellin"
													}
											],
											phone: "386-931-0368",
											title: "Arleen Mueller"
										},
										{ description: "GM, NAME Marketplaces",
											email: "maryvarg@name.com",
											groupTitleColor: "#4169e1",
											image: "e.png",
											itemTitleColor: "#4b0082",
											items: [ { description: "GM, Commerce Services & Marketplaces",
												email: "michdavi@name.com",
												groupTitleColor: "#4169e1",
												image: "r.png",
												itemTitleColor: "#4b0082",
												phone: "334-427-6507",
												title: "Michael Davis"
											} ],
											phone: "443-230-6107",
											title: "Mary Varga"
										},
										{ description: "GM, Product Management",
											email: "berntayl@name.com",
											groupTitleColor: "#4169e1",
											image: "t.png",
											itemTitleColor: "#4b0082",
											items: [ { description: "GM, NAME Search Strategy",
												email: "rosehens@name.com",
												groupTitleColor: "#4169e1",
												image: "y.png",
												itemTitleColor: "#4b0082",
												phone: "406-266-6063",
												title: "Rose Hensley"
											},
													{ description: "GM, Product Planning",
														email: "joselint@name.com",
														groupTitleColor: "#4169e1",
														image: "u.png",
														itemTitleColor: "#4b0082",
														phone: "541-620-4381",
														title: "Joseph Linthicum"
													}
											],
											phone: "918-725-7342",
											title: "Bernard Taylor"
										},
										{ description: "GM, spamCenter",
											email: "anthover@name.com",
											groupTitleColor: "#4169e1",
											image: "i.png",
											itemTitleColor: "#4b0082",
											phone: "914-733-3247",
											title: "Anthony Overstreet"
										}
								],
								phone: "425-590-4308",
								title: "Robert Lemieux"
							},
							{ description: "Chief of Staff, NAME",
								email: "danirich@name.com",
								groupTitleColor: "#4169e1",
								image: "o.png",
								itemTitleColor: "#4b0082",
								phone: "605-295-4417",
								title: "Daniel Richmond"
							}
					],
					phone: "915-355-4705",
					title: "Craig Blue"
				},
				{ description: "VP, Developer & Platform Fanatism",
					email: "allewall@name.com",
					groupTitleColor: "#4169e1",
					image: "p.png",
					itemTitleColor: "#4b0082",
					items: [ { description: "VP, .ORG Business Development",
						email: "benrobe@name.com",
						groupTitleColor: "#4169e1",
						image: "a.png",
						itemTitleColor: "#4b0082",
						items: [ { description: "GM, Emerging Business Market Development",
							email: "briapete@name.com",
							groupTitleColor: "#4169e1",
							image: "s.png",
							itemTitleColor: "#4b0082",
							phone: "215-328-8083",
							title: "Brian Peters"
						} ],
						phone: "636-827-5128",
						title: "Ben Roberson"
					},
							{ description: "GM, .ORG Platform Strategy",
								email: "mattcole@name.com",
								groupTitleColor: "#4169e1",
								image: "d.png",
								itemTitleColor: "#4b0082",
								phone: "408-978-8597",
								title: "Matthew Cole"
							},
							{ description: "GM, Global ISVs",
								email: "janemart@name.com",
								groupTitleColor: "#4169e1",
								image: "f.png",
								itemTitleColor: "#4b0082",
								items: [ { description: "GM, ISV Partner Ecosystems",
									email: "jasowall@name.com",
									groupTitleColor: "#4169e1",
									image: "g.png",
									itemTitleColor: "#4b0082",
									phone: "806-247-5956",
									title: "Jason Waller"
								} ],
								phone: "801-897-6086",
								title: "Janet Martin"
							},
							{ description: "GM, Platform Fanatism",
								email: "terecart@name.com",
								groupTitleColor: "#4169e1",
								image: "h.png",
								itemTitleColor: "#4b0082",
								phone: "770-326-1639",
								title: "Teresa Carter"
							}
					],
					phone: "480-472-4961",
					title: "Allen Wallace"
				},
				{ description: "Sr. VP, Software Client Business",
					email: "sallbarn@name.com",
					groupTitleColor: "#4169e1",
					image: "j.png",
					itemTitleColor: "#4b0082",
					items: [ { description: "VP, Digital Media Division",
						email: "elmopete@name.com",
						groupTitleColor: "#4169e1",
						image: "k.png",
						itemTitleColor: "#4b0082",
						items: [ { description: "GM, Photos and Imaging Experience Team",
							email: "lindrosa@name.com",
							groupTitleColor: "#4169e1",
							image: "l.png",
							itemTitleColor: "#4b0082",
							phone: "701-898-8879",
							title: "Linda Rosado"
						},
								{ description: "GM, Media Technology Group",
									email: "willnash@name.com",
									groupTitleColor: "#4169e1",
									image: "z.png",
									itemTitleColor: "#4b0082",
									phone: "213-841-9057",
									title: "William Nash"
								},
								{ description: "GM, Experience Excellence Team",
									email: "naomfree@name.com",
									groupTitleColor: "#4169e1",
									image: "x.png",
									itemTitleColor: "#4b0082",
									phone: "602-820-3322",
									title: "Naomi Freeman"
								},
								{ description: "GM, Software Media Experiences",
									email: "briawern@name.com",
									groupTitleColor: "#4169e1",
									image: "c.png",
									itemTitleColor: "#4b0082",
									phone: "540-833-9867",
									title: "Brian Werner"
								},
								{ description: "GM, DMD Consumer Media Ecosystem Team",
									email: "chrimay@name.com",
									groupTitleColor: "#4169e1",
									image: "v.png",
									itemTitleColor: "#4b0082",
									phone: "270-277-3906",
									title: "Christy May"
								}
						],
						phone: "423-307-1301",
						title: "Elmo Peterson"
					},
							{ description: "VP, Software Client Core Platform Team",
								email: "marinels@name.com",
								groupTitleColor: "#4169e1",
								image: "b.png",
								itemTitleColor: "#4b0082",
								items: [ { description: "GM, Internet Explorer",
									email: "desimoor@name.com",
									groupTitleColor: "#4169e1",
									image: "n.png",
									itemTitleColor: "#4b0082",
									phone: "413-684-4994",
									title: "Desiree Moore"
								},
										{ description: "GM, Software Graphics & Gaming Technologies",
											email: "michstev@name.com",
											groupTitleColor: "#4169e1",
											image: "m.png",
											itemTitleColor: "#4b0082",
											phone: "714-598-1630",
											title: "Micheal Stevens"
										},
										{ description: "GM, Software Client Platform",
											email: "jamestan@name.com",
											groupTitleColor: "#4169e1",
											image: "q.png",
											itemTitleColor: "#4b0082",
											phone: "410-895-3900",
											title: "James Stanley"
										}
								],
								phone: "410-325-4416",
								title: "Maria Nelson"
							},
							{ description: "VP, Software Online",
								email: "donnpott@name.com",
								groupTitleColor: "#4169e1",
								image: "w.png",
								itemTitleColor: "#4b0082",
								items: [ { description: "GM, Software Genuine Advantage",
									email: "tommedwa@name.com",
									groupTitleColor: "#4169e1",
									image: "e.png",
									itemTitleColor: "#4b0082",
									phone: "814-684-5370",
									title: "Tommie Edwards"
								} ],
								phone: "856-366-8761",
								title: "Donna Potts"
							},
							{ description: "VP, Software Product Management & Marketing",
								email: "nicklamb@name.com",
								groupTitleColor: "#4169e1",
								image: "r.png",
								itemTitleColor: "#4b0082",
								items: [ { description: "GM, Software Horror and Blackcomb Product Management",
									email: "marineal@name.com",
									groupTitleColor: "#4169e1",
									image: "t.png",
									itemTitleColor: "#4b0082",
									phone: "620-857-7223",
									title: "Marie Neal"
								},
										{ description: "GM, Emerging Markets",
											email: "johnklin@name.com",
											groupTitleColor: "#4169e1",
											image: "y.png",
											itemTitleColor: "#4b0082",
											phone: "858-792-9645",
											title: "John Kline"
										},
										{ description: "GM, Software Client Communications",
											email: "leotflow@name.com",
											groupTitleColor: "#4169e1",
											image: "u.png",
											itemTitleColor: "#4b0082",
											phone: "316-293-5909",
											title: "Leota Flowers"
										}
								],
								phone: "425-988-7714",
								title: "Nick Lambert"
							},
							{ description: "VP Software Client Extended Platforms",
								email: "danismal@name.com",
								groupTitleColor: "#4169e1",
								image: "i.png",
								itemTitleColor: "#4b0082",
								items: [ { description: "VP, Mobile Platforms Division",
									email: "jameburl@name.com",
									groupTitleColor: "#4169e1",
									image: "o.png",
									itemTitleColor: "#4b0082",
									items: [ { description: "GM, Mobile PCs & Tablet PCs",
										email: "bernwhit@name.com",
										groupTitleColor: "#4169e1",
										image: "p.png",
										itemTitleColor: "#4b0082",
										phone: "417-745-8910",
										title: "Bernice Whitlock"
									},
											{ description: "GM, Mobile Platforms Tools",
												email: "jeannoac@name.com",
												groupTitleColor: "#4169e1",
												image: "a.png",
												itemTitleColor: "#4b0082",
												phone: "925-871-8381",
												title: "Jean Noack"
											}
									],
									phone: "412-283-2101",
									title: "James Burleson"
								},
										{ description: "VP, Software eHome",
											email: "luisross@name.com",
											groupTitleColor: "#4169e1",
											image: "s.png",
											itemTitleColor: "#4b0082",
											items: [ { description: "GM, Connected TV",
												email: "marieste@name.com",
												groupTitleColor: "#4169e1",
												image: "d.png",
												itemTitleColor: "#4b0082",
												phone: "603-618-9475",
												title: "Maria Estes"
											} ],
											phone: "618-674-1369",
											title: "Luis Rosso"
										},
										{ description: "GM, Software TV",
											email: "justpins@name.com",
											groupTitleColor: "#4169e1",
											image: "f.png",
											itemTitleColor: "#4b0082",
											phone: "641-594-5378",
											title: "Justin Pinson"
										},
										{ description: "GM, Value Computing",
											email: "chrituck@name.com",
											groupTitleColor: "#4169e1",
											image: "g.png",
											itemTitleColor: "#4b0082",
											items: [ { description: "GM, Subscription and Prepaid Computing",
												email: "markdona@name.com",
												groupTitleColor: "#4169e1",
												image: "h.png",
												itemTitleColor: "#4b0082",
												phone: "207-382-9012",
												title: "Mark Donaldson"
											},
													{ description: "GM, Hardware Innovation Group",
														email: "donnedel@name.com",
														groupTitleColor: "#4169e1",
														image: "j.png",
														itemTitleColor: "#4b0082",
														phone: "267-323-1000",
														title: "Donna Edelen"
													}
											],
											phone: "860-373-6494",
											title: "Christina Tucker"
										}
								],
								phone: "469-977-1938",
								title: "Daniel Small"
							},
							{ description: "CFO, Software Client Business",
								email: "donngonz@name.com",
								groupTitleColor: "#4169e1",
								image: "k.png",
								itemTitleColor: "#4b0082",
								items: [ { description: "Sr. Controller, Client Business Group",
									email: "damoholm@name.com",
									groupTitleColor: "#4169e1",
									image: "l.png",
									itemTitleColor: "#4b0082",
									phone: "904-779-3511",
									title: "Damon Holmes"
								} ],
								phone: "213-763-3692",
								title: "Donnie Gonzalez"
							},
							{ description: "Chief of Staff, Software Client",
								email: "loriande@name.com",
								groupTitleColor: "#4169e1",
								image: "z.png",
								itemTitleColor: "#4b0082",
								phone: "863-858-4799",
								title: "Lori Anderson"
							}
					],
					phone: "319-656-8043",
					title: "Sally Barnes"
				},
				{ description: "Sr. Distinguished Engineer, Software Base Team",
					email: "lindwong@name.com",
					groupTitleColor: "#4169e1",
					image: "x.png",
					itemTitleColor: "#4b0082",
					phone: "201-925-1897",
					title: "Linda Wong"
				},
				{ description: "GM, Platforms Business Management",
					email: "bonnvald@name.com",
					groupTitleColor: "#4169e1",
					image: "c.png",
					itemTitleColor: "#4b0082",
					phone: "954-517-9979",
					title: "Bonnie Valdez"
				}
		],
		phone: "505-791-1689",
		title: "Jeanna White"
	},
			{ description: "President, Entertainment & Devices Division",
				email: "josegips@name.com",
				groupTitleColor: "#4169e1",
				image: "v.png",
				itemTitleColor: "#C57F7F",
				items: [ { description: "VP, Media",
					email: "chriwaug@name.com",
					groupTitleColor: "#4169e1",
					image: "b.png",
					itemTitleColor: "#C57F7F",
					items: [ { description: "GM, Media",
						email: "johnburr@name.com",
						groupTitleColor: "#4169e1",
						image: "n.png",
						itemTitleColor: "#C57F7F",
						phone: "864-334-6496",
						title: "John Burris"
					} ],
					phone: "323-924-6542",
					title: "Christine Waugh"
				},
						{ description: "CFO & VP, Entertainment",
							email: "ashlcaud@name.com",
							groupTitleColor: "#4169e1",
							image: "m.png",
							itemTitleColor: "#C57F7F",
							items: [ { description: "VP, Console Partnerships",
								email: "davigift@name.com",
								groupTitleColor: "#4169e1",
								image: "q.png",
								itemTitleColor: "#C57F7F",
								phone: "334-547-2141",
								title: "David Gift"
							},
									{ description: "VP, TV Division",
										email: "patrmitc@name.com",
										groupTitleColor: "#4169e1",
										image: "w.png",
										itemTitleColor: "#C57F7F",
										items: [ { description: "VP, Worldwide Sales & Services",
											email: "jasolibe@name.com",
											groupTitleColor: "#4169e1",
											image: "e.png",
											itemTitleColor: "#C57F7F",
											phone: "410-880-8511",
											title: "Jason Liberty"
										},
												{ description: "GM, MSTV Marketing",
													email: "shawsiko@name.com",
													groupTitleColor: "#4169e1",
													image: "r.png",
													itemTitleColor: "#C57F7F",
													phone: "505-658-1492",
													title: "Shawna Sikora"
												},
												{ description: "Chief of Staff, Name TV",
													email: "alexhill@name.com",
													groupTitleColor: "#4169e1",
													image: "t.png",
													itemTitleColor: "#C57F7F",
													phone: "910-647-9274",
													title: "Alex Hill"
												},
												{ description: "Chief Technology Officer and Engineering GM",
													email: "johnbarr@name.com",
													groupTitleColor: "#4169e1",
													image: "y.png",
													itemTitleColor: "#C57F7F",
													phone: "989-460-7440",
													title: "John Barrera"
												}
										],
										phone: "571-291-9887",
										title: "Patrick Mitchell"
									},
									{ description: "Controller, Entertainment & Devices Division",
										email: "fernbook@name.com",
										groupTitleColor: "#4169e1",
										image: "u.png",
										itemTitleColor: "#C57F7F",
										phone: "978-242-7739",
										title: "Fern Booker"
									}
							],
							phone: "785-468-7480",
							title: "Ashley Caudill"
						},
						{ description: "VP, Experiences & Design for Gaming and Entertainment",
							email: "steplowe@name.com",
							groupTitleColor: "#4169e1",
							image: "i.png",
							itemTitleColor: "#C57F7F",
							items: [ { description: "VP, Gaming and Console Platform Group",
								email: "ellemurp@name.com",
								groupTitleColor: "#4169e1",
								image: "o.png",
								itemTitleColor: "#C57F7F",
								items: [ { description: "GM, Game Developer Group",
									email: "patrfarr@name.com",
									groupTitleColor: "#4169e1",
									image: "p.png",
									itemTitleColor: "#C57F7F",
									phone: "307-600-7995",
									title: "Patricia Farr"
								},
										{ description: "GM, Console Platform",
											email: "josekrou@name.com",
											groupTitleColor: "#4169e1",
											image: "a.png",
											itemTitleColor: "#C57F7F",
											phone: "615-735-4453",
											title: "Joseph Krouse"
										}
								],
								phone: "478-221-9308",
								title: "Ellen Murphy"
							},
									{ description: "GM, Console Live Service Group",
										email: "delocoff@name.com",
										groupTitleColor: "#4169e1",
										image: "s.png",
										itemTitleColor: "#C57F7F",
										phone: "404-628-7275",
										title: "Delores Coffman"
									}
							],
							phone: "803-432-1532",
							title: "Stephen Lowe"
						},
						{ description: "VP, Retail Sales & Marketing",
							email: "jerrspur@name.com",
							groupTitleColor: "#4169e1",
							image: "d.png",
							itemTitleColor: "#C57F7F",
							items: [ { description: "VP, Entertainment & Devices",
								email: "chriwatt@name.com",
								groupTitleColor: "#4169e1",
								image: "f.png",
								itemTitleColor: "#C57F7F",
								phone: "248-522-9731",
								title: "Chris Watts"
							},
									{ description: "VP, Retail Sales & Marketing",
										email: "davikell@name.com",
										groupTitleColor: "#4169e1",
										image: "g.png",
										itemTitleColor: "#C57F7F",
										phone: "415-951-2949",
										title: "David Kelley"
									},
									{ description: "GM, Entertainment & Devices Division",
										email: "edgawalk@name.com",
										groupTitleColor: "#4169e1",
										image: "h.png",
										itemTitleColor: "#C57F7F",
										phone: "302-269-0651",
										title: "Edgar Walkup"
									}
							],
							phone: "305-819-4910",
							title: "Jerry Spurlock"
						},
						{ description: "Sr. VP, Mobile & Embedded Devices & Communications Sector",
							email: "thomdavi@name.com",
							groupTitleColor: "#4169e1",
							image: "j.png",
							itemTitleColor: "#C57F7F",
							items: [ { description: "VP, Communications Sector",
								email: "ignawidm@name.com",
								groupTitleColor: "#4169e1",
								image: "k.png",
								itemTitleColor: "#C57F7F",
								items: [ { description: "GM, Communications Sector Product & Solutions Group",
									email: "joshhall@name.com",
									groupTitleColor: "#4169e1",
									image: "l.png",
									itemTitleColor: "#C57F7F",
									items: [ { description: "GM, Service Enablement Product Group",
										email: "jasoanth@name.com",
										groupTitleColor: "#4169e1",
										image: "z.png",
										itemTitleColor: "#C57F7F",
										phone: "818-290-8097",
										title: "Jason Anthony"
									} ],
									phone: "972-455-1580",
									title: "Joshua Hall"
								},
										{ description: "GM, Communication Sector",
											email: "guydavi@name.com",
											groupTitleColor: "#4169e1",
											image: "x.png",
											itemTitleColor: "#C57F7F",
											phone: "509-663-3021",
											title: "Guy Davis"
										},
										{ description: "GM, Marketing and Customer Segments",
											email: "shelfriz@name.com",
											groupTitleColor: "#4169e1",
											image: "c.png",
											itemTitleColor: "#C57F7F",
											phone: "909-784-5859",
											title: "Shelley Frizzell"
										},
										{ description: "GM, Communications Sector",
											email: "paulteal@name.com",
											groupTitleColor: "#4169e1",
											image: "v.png",
											itemTitleColor: "#C57F7F",
											phone: "417-554-5877",
											title: "Paul Teal"
										},
										{ description: "GM, Hosting Solutions and SPLA Business",
											email: "toddgris@name.com",
											groupTitleColor: "#4169e1",
											image: "b.png",
											itemTitleColor: "#C57F7F",
											phone: "916-310-5044",
											title: "Todd Griswold"
										},
										{ description: "GM, Communications Sector",
											email: "edwaalba@name.com",
											groupTitleColor: "#4169e1",
											image: "n.png",
											itemTitleColor: "#C57F7F",
											items: [ { description: "GM, Communications Sector and Media & Entertainment",
												email: "danirodd@name.com",
												groupTitleColor: "#4169e1",
												image: "m.png",
												itemTitleColor: "#C57F7F",
												phone: "915-996-0159",
												title: "Daniel Roddy"
											} ],
											phone: "309-353-5220",
											title: "Edward Albarado"
										}
								],
								phone: "501-490-8654",
								title: "Ignacio Widmer"
							},
									{ description: "VP, Mobile and Embedded Device Marketing",
										email: "larrbell@name.com",
										groupTitleColor: "#4169e1",
										image: "q.png",
										itemTitleColor: "#C57F7F",
										items: [ { description: "GM, Software Mobile and Embedded Platforms",
											email: "carlrobi@name.com",
											groupTitleColor: "#4169e1",
											image: "w.png",
											itemTitleColor: "#C57F7F",
											phone: "845-729-6479",
											title: "Carlos Robinette"
										},
												{ description: "GM, Campaigns & Communications",
													email: "josegree@name.com",
													groupTitleColor: "#4169e1",
													image: "e.png",
													itemTitleColor: "#C57F7F",
													phone: "443-794-2552",
													title: "Joseph Green"
												}
										],
										phone: "260-704-4745",
										title: "Larry Bell"
									},
									{ description: "VP, Devices",
										email: "randshie@name.com",
										groupTitleColor: "#4169e1",
										image: "r.png",
										itemTitleColor: "#C57F7F",
										items: [ { description: "GM, Software Mobile",
											email: "lucafras@name.com",
											groupTitleColor: "#4169e1",
											image: "t.png",
											itemTitleColor: "#C57F7F",
											phone: "319-664-4631",
											title: "Lucas Fraser"
										},
												{ description: "GM, Mobile & Embedded devices (MED) Experience Team",
													email: "jackgagn@name.com",
													groupTitleColor: "#4169e1",
													image: "y.png",
													itemTitleColor: "#C57F7F",
													phone: "620-440-0276",
													title: "Jackie Gagne"
												},
												{ description: "GM, Development",
													email: "normflem@name.com",
													groupTitleColor: "#4169e1",
													image: "u.png",
													itemTitleColor: "#C57F7F",
													phone: "678-316-4170",
													title: "Norma Fleming"
												},
												{ description: "GM, Embedded & Devices Group",
													email: "bernpasc@name.com",
													groupTitleColor: "#4169e1",
													image: "i.png",
													itemTitleColor: "#C57F7F",
													phone: "530-618-1036",
													title: "Bernard Paschall"
												},
												{ description: "GM, Software CE Platforms Development",
													email: "sherpena@name.com",
													groupTitleColor: "#4169e1",
													image: "o.png",
													itemTitleColor: "#C57F7F",
													phone: "573-765-7098",
													title: "Sherri Pena"
												}
										],
										phone: "360-354-7598",
										title: "Randy Shields"
									},
									{ description: "CFO, Mobile & Embedded Devices & Communications Sector Division",
										email: "sarahayn@name.com",
										groupTitleColor: "#4169e1",
										image: "p.png",
										itemTitleColor: "#C57F7F",
										phone: "443-487-7347",
										title: "Sarah Haynes"
									}
							],
							phone: "313-722-8638",
							title: "Thomas Davidson"
						},
						{ description: "VP, Interactive Entertainment Business",
							email: "bettphil@name.com",
							groupTitleColor: "#4169e1",
							image: "a.png",
							itemTitleColor: "#C57F7F",
							items: [ { description: "GM, Global Marketing",
								email: "saraceba@name.com",
								groupTitleColor: "#4169e1",
								image: "s.png",
								itemTitleColor: "#C57F7F",
								phone: "701-385-7537",
								title: "Sara Ceballos"
							},
									{ description: "GM, New Media & Franchise Development",
										email: "lucimcdu@name.com",
										groupTitleColor: "#4169e1",
										image: "d.png",
										itemTitleColor: "#C57F7F",
										phone: "716-308-1312",
										title: "Lucius McDuffy"
									},
									{ description: "GM, Name Game Studios",
										email: "nicomcga@name.com",
										groupTitleColor: "#4169e1",
										image: "f.png",
										itemTitleColor: "#C57F7F",
										items: [ { description: "GM",
											email: "robemart@name.com",
											groupTitleColor: "#4169e1",
											image: "g.png",
											itemTitleColor: "#C57F7F",
											phone: "563-783-0278",
											title: "Robert Martin"
										},
												{ description: "GM",
													email: "kevidupp@name.com",
													groupTitleColor: "#4169e1",
													image: "h.png",
													itemTitleColor: "#C57F7F",
													phone: "812-227-7850",
													title: "Kevin Duppstadt"
												},
												{ description: "GM",
													email: "verndrap@name.com",
													groupTitleColor: "#4169e1",
													image: "j.png",
													itemTitleColor: "#C57F7F",
													phone: "912-235-1438",
													title: "Vernell Draper"
												},
												{ description: "GM",
													email: "olgamill@name.com",
													groupTitleColor: "#4169e1",
													image: "k.png",
													itemTitleColor: "#C57F7F",
													phone: "828-326-7585",
													title: "Olga Miller"
												}
										],
										phone: "315-837-8910",
										title: "Nicole McGahey"
									},
									{ description: "GM, Entertainment & Devices",
										email: "rickbron@name.com",
										groupTitleColor: "#4169e1",
										image: "l.png",
										itemTitleColor: "#C57F7F",
										phone: "323-877-8571",
										title: "Ricky Bronk"
									}
							],
							phone: "443-564-5549",
							title: "Bettyann Phillips"
						},
						{ description: "VP, Consumer Productivity eXperierences Division",
							email: "doripont@name.com",
							groupTitleColor: "#4169e1",
							image: "z.png",
							itemTitleColor: "#C57F7F",
							items: [ { description: "GM, North America Operations",
								email: "samutibb@name.com",
								groupTitleColor: "#4169e1",
								image: "x.png",
								itemTitleColor: "#C57F7F",
								items: [ { description: "GM, Entertainment & Devices Systems",
									email: "jennsnyd@name.com",
									groupTitleColor: "#4169e1",
									image: "c.png",
									itemTitleColor: "#C57F7F",
									phone: "971-247-6345",
									title: "Jennifer Snyder"
								},
										{ description: "GM, North America Consumer Operations",
											email: "eugefoch@name.com",
											groupTitleColor: "#4169e1",
											image: "v.png",
											itemTitleColor: "#C57F7F",
											phone: "269-586-0636",
											title: "Eugene Focht"
										}
								],
								phone: "406-881-5323",
								title: "Samuel Tibbs"
							},
									{ description: "GM, Entertainment & Devices Localization and Shared Services",
										email: "jamerede@name.com",
										groupTitleColor: "#4169e1",
										image: "b.png",
										itemTitleColor: "#C57F7F",
										phone: "612-866-4856",
										title: "James Reder"
									},
									{ description: "GM, Consumer Software",
										email: "marymcle@name.com",
										groupTitleColor: "#4169e1",
										image: "n.png",
										itemTitleColor: "#C57F7F",
										items: [ { description: "GM, Learning Business Unit",
											email: "rachtros@name.com",
											groupTitleColor: "#4169e1",
											image: "m.png",
											itemTitleColor: "#C57F7F",
											phone: "312-334-5543",
											title: "Rachel Trost"
										} ],
										phone: "707-784-6254",
										title: "Mary McLendon"
									},
									{ description: "GM, Macintosh Business Unit",
										email: "versalle@name.com",
										groupTitleColor: "#4169e1",
										image: "q.png",
										itemTitleColor: "#C57F7F",
										phone: "810-371-1010",
										title: "Versie Allen"
									},
									{ description: "GM, Hardware",
										email: "dianwill@name.com",
										groupTitleColor: "#4169e1",
										image: "w.png",
										itemTitleColor: "#C57F7F",
										phone: "520-287-8249",
										title: "Diann Williamson"
									}
							],
							phone: "916-418-3715",
							title: "Doris Ponte"
						}
				],
				phone: "817-350-5277",
				title: "Joseph Gipson"
			},
			{ description: "Sr. VP, General Counsel & Secretary",
				email: "florbutt@name.com",
				groupTitleColor: "#4169e1",
				image: "e.png",
				itemTitleColor: "#32cd32",
				items: [ { description: "VP & Deputy General Counsel, Platforms Products & Services",
					email: "davihedb@name.com",
					groupTitleColor: "#4169e1",
					image: "r.png",
					itemTitleColor: "#32cd32",
					phone: "801-316-7533",
					title: "David Hedberg"
				},
						{ description: "VP & Deputy General Counsel, IP & Licensing",
							email: "brucclif@name.com",
							groupTitleColor: "#4169e1",
							image: "t.png",
							itemTitleColor: "#32cd32",
							items: [ { description: "GM, Business Development",
								email: "josemeis@name.com",
								groupTitleColor: "#4169e1",
								image: "y.png",
								itemTitleColor: "#32cd32",
								phone: "760-672-2080",
								title: "Josephine Meister"
							},
									{ description: "GM, Patents & IP",
										email: "branarms@name.com",
										groupTitleColor: "#4169e1",
										image: "u.png",
										itemTitleColor: "#32cd32",
										phone: "832-496-0315",
										title: "Brandon Armstrong"
									},
									{ description: "GM, Corporate Standards",
										email: "bertruck@name.com",
										groupTitleColor: "#4169e1",
										image: "i.png",
										itemTitleColor: "#32cd32",
										phone: "773-719-3488",
										title: "Berta Rucker"
									}
							],
							phone: "918-485-2318",
							title: "Bruce Clift"
						},
						{ description: "VP, & Deputy General Counsel",
							email: "arthbuck@name.com",
							groupTitleColor: "#4169e1",
							image: "o.png",
							itemTitleColor: "#32cd32",
							phone: "724-244-6527",
							title: "Arthur Buck"
						},
						{ description: "Deputy General Counsel, Antitrust",
							email: "jameturn@name.com",
							groupTitleColor: "#4169e1",
							image: "p.png",
							itemTitleColor: "#32cd32",
							phone: "620-362-3063",
							title: "James Turner"
						},
						{ description: "VP & Deputy General Counsel, Business Division",
							email: "michharr@name.com",
							groupTitleColor: "#4169e1",
							image: "a.png",
							itemTitleColor: "#32cd32",
							phone: "508-241-0717",
							title: "Michelle Harr"
						},
						{ description: "Deputy General Counsel, Office of Legal Compliance",
							email: "demekenn@name.com",
							groupTitleColor: "#4169e1",
							image: "s.png",
							itemTitleColor: "#32cd32",
							phone: "239-878-8236",
							title: "Demetrice Kenney"
						},
						{ description: "VP, & Deputy General Counsel",
							email: "markbarr@name.com",
							groupTitleColor: "#4169e1",
							image: "d.png",
							itemTitleColor: "#32cd32",
							phone: "312-485-4776",
							title: "Mark Barreto"
						},
						{ description: "Deputy General Counsel, Law & Corporate Affairs (LCA) Operations",
							email: "jennhurt@name.com",
							groupTitleColor: "#4169e1",
							image: "f.png",
							itemTitleColor: "#32cd32",
							phone: "503-355-4165",
							title: "Jennifer Hurtt"
						},
						{ description: "VP & Deputy General Counsel, Worldwide Sales",
							email: "chrimaur@name.com",
							groupTitleColor: "#4169e1",
							image: "g.png",
							itemTitleColor: "#32cd32",
							phone: "727-426-1652",
							title: "Christopher Mauro"
						},
						{ description: "VP & Deputy General Counsel, Global Corporate Affairs",
							email: "paulmcki@name.com",
							groupTitleColor: "#4169e1",
							image: "h.png",
							itemTitleColor: "#32cd32",
							phone: "603-446-2403",
							title: "Paul McKissick"
						},
						{ description: "VP & Deputy General Counsel, Entertainment & Devices",
							email: "janehamm@name.com",
							groupTitleColor: "#4169e1",
							image: "j.png",
							itemTitleColor: "#32cd32",
							phone: "903-296-5810",
							title: "Jane Hammond"
						}
				],
				phone: "802-214-1030",
				title: "Florence Butts"
			},
			{ description: "President, Business Division",
				email: "jamenunn@name.com",
				groupTitleColor: "#4169e1",
				image: "k.png",
				itemTitleColor: "#ffa500",
				items: [ { description: "VP, Unified Communications Group",
					email: "shelnies@name.com",
					groupTitleColor: "#4169e1",
					image: "l.png",
					itemTitleColor: "#ffa500",
					items: [ { description: "VP, Collaboration Server",
						email: "tommgonz@name.com",
						groupTitleColor: "#4169e1",
						image: "z.png",
						itemTitleColor: "#ffa500",
						items: [ { description: "GM, Collaboration Hosted Services",
							email: "jermwhit@name.com",
							groupTitleColor: "#4169e1",
							image: "x.png",
							itemTitleColor: "#ffa500",
							phone: "412-466-4767",
							title: "Jermaine White"
						},
								{ description: "GM, Emerging Server Team",
									email: "consrose@name.com",
									groupTitleColor: "#4169e1",
									image: "c.png",
									itemTitleColor: "#ffa500",
									phone: "610-874-6947",
									title: "Constance Rose"
								},
								{ description: "GM, Collaboration",
									email: "roryterr@name.com",
									groupTitleColor: "#4169e1",
									image: "v.png",
									itemTitleColor: "#ffa500",
									phone: "607-490-8476",
									title: "Rory Terry"
								}
						],
						phone: "561-741-0904",
						title: "Tommy Gonzalez"
					},
							{ description: "VP, Distributed Meetings",
								email: "joanseth@name.com",
								groupTitleColor: "#4169e1",
								image: "b.png",
								itemTitleColor: "#ffa500",
								items: [ { description: "GM, RoundTable",
									email: "ayanfuen@name.com",
									groupTitleColor: "#4169e1",
									image: "n.png",
									itemTitleColor: "#ffa500",
									phone: "661-545-5311",
									title: "Ayana Fuentes"
								} ],
								phone: "320-585-1870",
								title: "Joan Seth"
							},
							{ description: "GM, Sales & Marketing",
								email: "johnspin@name.com",
								groupTitleColor: "#4169e1",
								image: "m.png",
								itemTitleColor: "#ffa500",
								phone: "615-531-3851",
								title: "John Spinks"
							},
							{ description: "GM, Live Meeting Services",
								email: "charwern@name.com",
								groupTitleColor: "#4169e1",
								image: "q.png",
								itemTitleColor: "#ffa500",
								phone: "323-305-6987",
								title: "Charles Werner"
							},
							{ description: "GM, Collaboration Marketing",
								email: "davihine@name.com",
								groupTitleColor: "#4169e1",
								image: "w.png",
								itemTitleColor: "#ffa500",
								phone: "580-934-0875",
								title: "David Hines"
							},
							{ description: "GM, Worldwide Marketing & Business Development",
								email: "derrjohn@name.com",
								groupTitleColor: "#4169e1",
								image: "e.png",
								itemTitleColor: "#ffa500",
								phone: "305-211-4511",
								title: "Derrick Johnson"
							}
					],
					phone: "757-289-6478",
					title: "Shelly Nies"
				},
						{ description: "VP, Information Worker Product Management Group (IWPMG)",
							email: "stevrick@name.com",
							groupTitleColor: "#4169e1",
							image: "r.png",
							itemTitleColor: "#ffa500",
							items: [ { description: "GM, Business Strategy",
								email: "willholm@name.com",
								groupTitleColor: "#4169e1",
								image: "t.png",
								itemTitleColor: "#ffa500",
								phone: "317-788-4007",
								title: "William Holmes"
							},
									{ description: "GM, Business Strategy",
										email: "jonawhit@name.com",
										groupTitleColor: "#4169e1",
										image: "y.png",
										itemTitleColor: "#ffa500",
										phone: "619-331-4876",
										title: "Jonathan White"
									},
									{ description: "GM, Groove Product Management Group",
										email: "rondmill@name.com",
										groupTitleColor: "#4169e1",
										image: "u.png",
										itemTitleColor: "#ffa500",
										phone: "832-433-4367",
										title: "Ronda Miller"
									},
									{ description: "GM, Information Worker Field and Partner Marketing",
										email: "donapowe@name.com",
										groupTitleColor: "#4169e1",
										image: "i.png",
										itemTitleColor: "#ffa500",
										items: [ { description: "VP, Information Worker Business Value",
											email: "ethejohn@name.com",
											groupTitleColor: "#4169e1",
											image: "o.png",
											itemTitleColor: "#ffa500",
											phone: "617-624-2283",
											title: "Ethel Johnston"
										} ],
										phone: "973-210-6895",
										title: "Donald Powell"
									},
									{ description: "GM, IW Product Management",
										email: "chriwint@name.com",
										groupTitleColor: "#4169e1",
										image: "p.png",
										itemTitleColor: "#ffa500",
										phone: "734-429-7943",
										title: "Christina Winters"
									},
									{ description: "GM, Office System Product Management",
										email: "tiffscol@name.com",
										groupTitleColor: "#4169e1",
										image: "a.png",
										itemTitleColor: "#ffa500",
										phone: "503-223-8526",
										title: "Tiffany Scoles"
									}
							],
							phone: "215-532-1237",
							title: "Steven Rickard"
						},
						{ description: "Chairman, MBS",
							email: "seanmill@name.com",
							groupTitleColor: "#4169e1",
							image: "s.png",
							itemTitleColor: "#ffa500",
							phone: "620-228-3102",
							title: "Sean Milligan"
						},
						{ description: "VP, Office Business Applications",
							email: "franhowl@name.com",
							groupTitleColor: "#4169e1",
							image: "d.png",
							itemTitleColor: "#ffa500",
							items: [ { description: "GM, Office Business Intelligence Applications",
								email: "edwaclar@name.com",
								groupTitleColor: "#4169e1",
								image: "f.png",
								itemTitleColor: "#ffa500",
								phone: "615-460-7145",
								title: "Edward Clark"
							},
									{ description: "GM, Office Business Applications",
										email: "georwill@name.com",
										groupTitleColor: "#4169e1",
										image: "g.png",
										itemTitleColor: "#ffa500",
										phone: "315-665-6459",
										title: "George Williams"
									},
									{ description: "GM, Name Office Business Applications",
										email: "bernhash@name.com",
										groupTitleColor: "#4169e1",
										image: "h.png",
										itemTitleColor: "#ffa500",
										phone: "202-334-2711",
										title: "Bernard Hash"
									}
							],
							phone: "918-516-8423",
							title: "Francis Howlett"
						},
						{ description: "Sr. VP, Office",
							email: "andrplou@name.com",
							groupTitleColor: "#4169e1",
							image: "j.png",
							itemTitleColor: "#ffa500",
							items: [ { description: "VP, Office Shared Services Program Management",
								email: "edkief@name.com",
								groupTitleColor: "#4169e1",
								image: "k.png",
								itemTitleColor: "#ffa500",
								phone: "606-613-3945",
								title: "Ed Kieffer"
							},
									{ description: "VP, Office Shared Services Test & Operations",
										email: "odellock@name.com",
										groupTitleColor: "#4169e1",
										image: "l.png",
										itemTitleColor: "#ffa500",
										phone: "417-229-2199",
										title: "Odelia Locker"
									},
									{ description: "VP, Office Server Group",
										email: "johnsmit@name.com",
										groupTitleColor: "#4169e1",
										image: "z.png",
										itemTitleColor: "#ffa500",
										items: [ { description: "GM, FrontPage",
											email: "tonykyle@name.com",
											groupTitleColor: "#4169e1",
											image: "x.png",
											itemTitleColor: "#ffa500",
											phone: "201-765-6133",
											title: "Tonya Kyle"
										},
												{ description: "GM, Business Portals Group",
													email: "dougfrie@name.com",
													groupTitleColor: "#4169e1",
													image: "c.png",
													itemTitleColor: "#ffa500",
													phone: "319-440-4862",
													title: "Douglas Friel"
												},
												{ description: "GM, Project Business Unit",
													email: "gordallm@name.com",
													groupTitleColor: "#4169e1",
													image: "v.png",
													itemTitleColor: "#ffa500",
													phone: "256-580-6101",
													title: "Gordon Allman"
												}
										],
										phone: "503-727-1970",
										title: "John Smith"
									},
									{ description: "VP, Office Authoring Services",
										email: "jeffhawk@name.com",
										groupTitleColor: "#4169e1",
										image: "b.png",
										itemTitleColor: "#ffa500",
										items: [ { description: "GM, Works",
											email: "jesssimp@name.com",
											groupTitleColor: "#4169e1",
											image: "n.png",
											itemTitleColor: "#ffa500",
											phone: "281-542-2564",
											title: "Jessica Simpson"
										},
												{ description: "GM, Speech & Natural Language",
													email: "annijone@name.com",
													groupTitleColor: "#4169e1",
													image: "m.png",
													itemTitleColor: "#ffa500",
													phone: "314-303-8394",
													title: "Annie Jones"
												}
										],
										phone: "513-273-8477",
										title: "Jeffrey Hawkins"
									},
									{ description: "VP, Office Data & Business Intelligence Services",
										email: "wensutt@name.com",
										groupTitleColor: "#4169e1",
										image: "q.png",
										itemTitleColor: "#ffa500",
										phone: "317-390-2215",
										title: "Wen Sutton"
									},
									{ description: "President & GM, Name Product Development Japan",
										email: "amypalo@name.com",
										groupTitleColor: "#4169e1",
										image: "w.png",
										itemTitleColor: "#ffa500",
										phone: "850-231-8168",
										title: "Amy Palomares"
									},
									{ description: "GM, Office Management & Update Services",
										email: "briawynn@name.com",
										groupTitleColor: "#4169e1",
										image: "e.png",
										itemTitleColor: "#ffa500",
										phone: "570-455-4491",
										title: "Brian Wynne"
									},
									{ description: "GM, Assistance & Worldwide Services",
										email: "nichgetz@name.com",
										groupTitleColor: "#4169e1",
										image: "r.png",
										itemTitleColor: "#ffa500",
										items: [ { description: "GM, Assistance Platform",
											email: "josebean@name.com",
											groupTitleColor: "#4169e1",
											image: "t.png",
											itemTitleColor: "#ffa500",
											phone: "440-701-3726",
											title: "Joseph Bean"
										} ],
										phone: "785-459-7906",
										title: "Nicholas Getz"
									},
									{ description: "GM, Office Graphics Services",
										email: "jamimenj@name.com",
										groupTitleColor: "#4169e1",
										image: "y.png",
										itemTitleColor: "#ffa500",
										phone: "707-665-4284",
										title: "Jamila Menjivar"
									},
									{ description: "GM, Office Communication Services",
										email: "chriwick@name.com",
										groupTitleColor: "#4169e1",
										image: "u.png",
										itemTitleColor: "#ffa500",
										phone: "330-562-1886",
										title: "Christy Wickline"
									}
							],
							phone: "781-878-1954",
							title: "Andrew Plourde"
						},
						{ description: "Sr. VP, Name Business Solutions (MBS)",
							email: "margwedd@name.com",
							groupTitleColor: "#4169e1",
							image: "i.png",
							itemTitleColor: "#ffa500",
							items: [ { description: "VP, Business Development",
								email: "milaroma@name.com",
								groupTitleColor: "#4169e1",
								image: "o.png",
								itemTitleColor: "#ffa500",
								items: [ { description: "GM, FRx",
									email: "michbate@name.com",
									groupTitleColor: "#4169e1",
									image: "p.png",
									itemTitleColor: "#ffa500",
									phone: "530-865-6311",
									title: "Michael Bates"
								} ],
								phone: "415-720-7283",
								title: "Milagros Roman"
							},
									{ description: "Sr. VP, WW Small & Midmarket Solutions & Partners",
										email: "byroiron@name.com",
										groupTitleColor: "#4169e1",
										image: "a.png",
										itemTitleColor: "#ffa500",
										items: [ { description: "VP, WW Partner Group and WW Small Business Group",
											email: "cyntleon@name.com",
											groupTitleColor: "#4169e1",
											image: "s.png",
											itemTitleColor: "#ffa500",
											items: [ { description: "GM, Partner Sales and Readiness",
												email: "nicogrim@name.com",
												groupTitleColor: "#4169e1",
												image: "d.png",
												itemTitleColor: "#ffa500",
												phone: "561-653-1957",
												title: "Nicolas Grimes"
											},
													{ description: "GM, Small Business",
														email: "delonico@name.com",
														groupTitleColor: "#4169e1",
														image: "f.png",
														itemTitleColor: "#ffa500",
														phone: "603-780-3340",
														title: "Delores Nicola"
													},
													{ description: "GM, WW Partner Marketing",
														email: "malilamb@name.com",
														groupTitleColor: "#4169e1",
														image: "g.png",
														itemTitleColor: "#ffa500",
														phone: "949-202-9709",
														title: "Malinda Lamberth"
													},
													{ description: "GM, Name Partner Program",
														email: "tonybrun@name.com",
														groupTitleColor: "#4169e1",
														image: "h.png",
														itemTitleColor: "#ffa500",
														phone: "570-997-7290",
														title: "Tonya Bruno"
													},
													{ description: "GM, Partner Velocity Platform",
														email: "richponc@name.com",
														groupTitleColor: "#4169e1",
														image: "j.png",
														itemTitleColor: "#ffa500",
														phone: "207-523-7569",
														title: "Richard Ponce"
													}
											],
											phone: "773-742-0844",
											title: "Cynthia Leon"
										},
												{ description: "VP, MBS Sales Strategy",
													email: "hectdade@name.com",
													groupTitleColor: "#4169e1",
													image: "k.png",
													itemTitleColor: "#ffa500",
													phone: "858-952-5612",
													title: "Hector Dade"
												},
												{ description: "VP, Midmarket Sales and Marketing",
													email: "lucisurb@name.com",
													groupTitleColor: "#4169e1",
													image: "l.png",
													itemTitleColor: "#ffa500",
													items: [ { description: "GM, WW Midmarket Marketing",
														email: "robeduke@name.com",
														groupTitleColor: "#4169e1",
														image: "z.png",
														itemTitleColor: "#ffa500",
														phone: "706-243-6765",
														title: "Robert Duke"
													},
															{ description: "GM, Midmarket Sales Strategy",
																email: "rosemich@name.com",
																groupTitleColor: "#4169e1",
																image: "x.png",
																itemTitleColor: "#ffa500",
																phone: "410-474-3014",
																title: "Rosemary Michaels"
															}
													],
													phone: "601-664-9469",
													title: "Lucille Surber"
												},
												{ description: "VP, System Builder and License Compliance",
													email: "earlthom@name.com",
													groupTitleColor: "#4169e1",
													image: "c.png",
													itemTitleColor: "#ffa500",
													phone: "804-416-0404",
													title: "Earl Thomas"
												},
												{ description: "VP, Marketing & Strategy",
													email: "robevele@name.com",
													groupTitleColor: "#4169e1",
													image: "v.png",
													itemTitleColor: "#ffa500",
													items: [ { description: "GM, CRM",
														email: "dennmart@name.com",
														groupTitleColor: "#4169e1",
														image: "b.png",
														itemTitleColor: "#ffa500",
														phone: "417-841-6959",
														title: "Dennis Martz"
													},
															{ description: "GM, Dynamics Marketing",
																email: "rosafenl@name.com",
																groupTitleColor: "#4169e1",
																image: "n.png",
																itemTitleColor: "#ffa500",
																phone: "810-579-8744",
																title: "Rosalyn Fenley"
															},
															{ description: "GM, Dynamics GP and SL",
																email: "kentpend@name.com",
																groupTitleColor: "#4169e1",
																image: "m.png",
																itemTitleColor: "#ffa500",
																phone: "205-447-1343",
																title: "Kent Pendleton"
															},
															{ description: "GM, Axapta",
																email: "ryaneddi@name.com",
																groupTitleColor: "#4169e1",
																image: "q.png",
																itemTitleColor: "#ffa500",
																phone: "865-539-2944",
																title: "Ryan Eddington"
															},
															{ description: "GM, Global Marketing",
																email: "normbrow@name.com",
																groupTitleColor: "#4169e1",
																image: "w.png",
																itemTitleColor: "#ffa500",
																phone: "205-206-4008",
																title: "Norma Brown"
															},
															{ description: "GM, Name Business Solutions",
																email: "louilewi@name.com",
																groupTitleColor: "#4169e1",
																image: "e.png",
																itemTitleColor: "#ffa500",
																phone: "845-487-7677",
																title: "Louisa Lewis"
															}
													],
													phone: "740-549-8621",
													title: "Robert Velez"
												},
												{ description: "GM, Business Group Operations",
													email: "jesscoll@name.com",
													groupTitleColor: "#4169e1",
													image: "r.png",
													itemTitleColor: "#ffa500",
													phone: "650-696-8452",
													title: "Jessica Collins"
												}
										],
										phone: "708-477-1975",
										title: "Byron Irons"
									},
									{ description: "VP, Name Business Solutions",
										email: "patralle@name.com",
										groupTitleColor: "#4169e1",
										image: "t.png",
										itemTitleColor: "#ffa500",
										items: [ { description: "GM, Dynamics Tools",
											email: "jesudibb@name.com",
											groupTitleColor: "#4169e1",
											image: "y.png",
											itemTitleColor: "#ffa500",
											phone: "337-636-6853",
											title: "Jesus Dibble"
										},
												{ description: "GM, Customer Relationship Management Business Unit",
													email: "annjack@name.com",
													groupTitleColor: "#4169e1",
													image: "u.png",
													itemTitleColor: "#ffa500",
													phone: "718-842-3643",
													title: "Ann Jackson"
												},
												{ description: "GM, Name ERP Product Group",
													email: "barralle@name.com",
													groupTitleColor: "#4169e1",
													image: "i.png",
													itemTitleColor: "#ffa500",
													phone: "415-532-7262",
													title: "Barry Allen"
												},
												{ description: "GM, Global Delivery Team",
													email: "jametayl@name.com",
													groupTitleColor: "#4169e1",
													image: "o.png",
													itemTitleColor: "#ffa500",
													phone: "502-652-1422",
													title: "James Taylor"
												},
												{ description: "GM, Midmarket Solutions",
													email: "sandmcca@name.com",
													groupTitleColor: "#4169e1",
													image: "p.png",
													itemTitleColor: "#ffa500",
													phone: "614-534-5004",
													title: "Sandi McCarty"
												},
												{ description: "GM, Supply Chain Management",
													email: "roylau@name.com",
													groupTitleColor: "#4169e1",
													image: "a.png",
													itemTitleColor: "#ffa500",
													phone: "215-546-7601",
													title: "Roy Lau"
												},
												{ description: "GM, Small Business & Online Applications",
													email: "shirwinc@name.com",
													groupTitleColor: "#4169e1",
													image: "s.png",
													itemTitleColor: "#ffa500",
													items: [ { description: "GM, Small Business Commerce",
														email: "brenhill@name.com",
														groupTitleColor: "#4169e1",
														image: "d.png",
														itemTitleColor: "#ffa500",
														phone: "620-547-0255",
														title: "Brent Hill"
													} ],
													phone: "714-314-0300",
													title: "Shirley Winchester"
												}
										],
										phone: "478-397-9217",
										title: "Patricia Allen"
									},
									{ description: "CFO, MBS",
										email: "bobble@name.com",
										groupTitleColor: "#4169e1",
										image: "f.png",
										itemTitleColor: "#ffa500",
										phone: "989-727-0218",
										title: "Bobbi Le"
									}
							],
							phone: "818-917-7110",
							title: "Marguerite Weddle"
						},
						{ description: "GM, IW New Markets Incubations",
							email: "cherbruc@name.com",
							groupTitleColor: "#4169e1",
							image: "g.png",
							itemTitleColor: "#ffa500",
							phone: "978-992-8399",
							title: "Cheryl Bruce"
						},
						{ description: "GM, IW Adoption Group",
							email: "marcbarb@name.com",
							groupTitleColor: "#4169e1",
							image: "h.png",
							itemTitleColor: "#ffa500",
							phone: "425-233-0233",
							title: "Marc Barber"
						},
						{ description: "CFO, Business Division",
							email: "charlips@name.com",
							groupTitleColor: "#4169e1",
							image: "j.png",
							itemTitleColor: "#ffa500",
							phone: "847-878-3093",
							title: "Charles Lipsey"
						},
						{ description: "GM, Information Worker Services",
							email: "georcahi@name.com",
							groupTitleColor: "#4169e1",
							image: "k.png",
							itemTitleColor: "#ffa500",
							items: [ { description: "GM, Information Worker Services",
								email: "stacwhit@name.com",
								groupTitleColor: "#4169e1",
								image: "l.png",
								itemTitleColor: "#ffa500",
								phone: "859-461-8006",
								title: "Stacey White"
							} ],
							phone: "763-441-7062",
							title: "Georgina Cahill"
						},
						{ description: "Business Manager, Business Division",
							email: "heatpowe@name.com",
							groupTitleColor: "#4169e1",
							image: "z.png",
							itemTitleColor: "#ffa500",
							phone: "931-200-4648",
							title: "Heather Powell"
						}
				],
				phone: "414-411-9368",
				title: "James Nunnally"
			},
			{ description: "Sr. VP & CFO",
				email: "franhuyn@name.com",
				groupTitleColor: "#4169e1",
				image: "x.png",
				itemTitleColor: "#E64848",
				items: [ { description: "VP, Treasurer",
					email: "herbprui@name.com",
					groupTitleColor: "#4169e1",
					image: "c.png",
					itemTitleColor: "#E64848",
					phone: "339-226-1956",
					title: "Herbert Pruitt"
				},
						{ description: "VP, Finance",
							email: "patrflem@name.com",
							groupTitleColor: "#4169e1",
							image: "v.png",
							itemTitleColor: "#E64848",
							items: [ { description: "VP, Worldwide Income Taxes",
								email: "harograv@name.com",
								groupTitleColor: "#4169e1",
								image: "b.png",
								itemTitleColor: "#E64848",
								phone: "804-524-1013",
								title: "Harold Graves"
							},
									{ description: "Tax Counsel",
										email: "mikereye@name.com",
										groupTitleColor: "#4169e1",
										image: "n.png",
										itemTitleColor: "#E64848",
										phone: "908-575-1146",
										title: "Mike Reyes"
									},
									{ description: "General Auditor",
										email: "florkuyk@name.com",
										groupTitleColor: "#4169e1",
										image: "m.png",
										itemTitleColor: "#E64848",
										phone: "407-419-2452",
										title: "Florence Kuykendall"
									}
							],
							phone: "217-376-3240",
							title: "Patricia Fleming"
						},
						{ description: "VP, Corp. Strategy Planning & Analysis",
							email: "jessgood@name.com",
							groupTitleColor: "#4169e1",
							image: "q.png",
							itemTitleColor: "#E64848",
							items: [ { description: "GM, Corporate Forecasting",
								email: "timmccr@name.com",
								groupTitleColor: "#4169e1",
								image: "w.png",
								itemTitleColor: "#E64848",
								phone: "270-748-0925",
								title: "Tim McCracken"
							},
									{ description: "GM, Venture Integration",
										email: "everthom@name.com",
										groupTitleColor: "#4169e1",
										image: "e.png",
										itemTitleColor: "#E64848",
										phone: "701-250-2141",
										title: "Everett Thompson"
									}
							],
							phone: "512-986-9095",
							title: "Jessica Goodwin"
						},
						{ description: "VP, Finance & Administration and Chief Accounting Officer",
							email: "gailshar@name.com",
							groupTitleColor: "#4169e1",
							image: "r.png",
							itemTitleColor: "#E64848",
							items: [ { description: "Controller, Corporate Services and HR",
								email: "christjo@name.com",
								groupTitleColor: "#4169e1",
								image: "t.png",
								itemTitleColor: "#E64848",
								phone: "734-272-4201",
								title: "Christopher Stjohn"
							},
									{ description: "GM, Corporate Services",
										email: "willyoun@name.com",
										groupTitleColor: "#4169e1",
										image: "y.png",
										itemTitleColor: "#E64848",
										items: [ { description: "GM, Real Estate & Facilities",
											email: "scotturp@name.com",
											groupTitleColor: "#4169e1",
											image: "u.png",
											itemTitleColor: "#E64848",
											phone: "407-927-1049",
											title: "Scott Turpin"
										} ],
										phone: "203-238-6625",
										title: "William Young"
									},
									{ description: "Controller, LCA and Exec. Finance",
										email: "donhubb@name.com",
										groupTitleColor: "#4169e1",
										image: "i.png",
										itemTitleColor: "#E64848",
										phone: "361-234-6292",
										title: "Don Hubbard"
									},
									{ description: "Assistant Corporate Controller",
										email: "thommoor@name.com",
										groupTitleColor: "#4169e1",
										image: "o.png",
										itemTitleColor: "#E64848",
										phone: "469-713-2162",
										title: "Thomas Moore"
									},
									{ description: "Controller, Global Platforms & Operations",
										email: "hazenewt@name.com",
										groupTitleColor: "#4169e1",
										image: "p.png",
										itemTitleColor: "#E64848",
										phone: "386-672-7474",
										title: "Hazel Newton"
									}
							],
							phone: "408-492-6216",
							title: "Gail Sharpless"
						},
						{ description: "Managing Dir., Corporate Development",
							email: "robegray@name.com",
							groupTitleColor: "#4169e1",
							image: "a.png",
							itemTitleColor: "#E64848",
							phone: "860-894-8438",
							title: "Robert Gray"
						}
				],
				phone: "404-347-5968",
				title: "Fran Huynh"
			},
			{ description: "Sr. VP, Strategy & Partnerships",
				email: "harrhart@name.com",
				groupTitleColor: "#4169e1",
				image: "s.png",
				itemTitleColor: "#808000",
				phone: "270-991-8539",
				title: "Harry Harter"
			},
			{ description: "Sr. VP, Human Resources",
				email: "krisnels@name.com",
				groupTitleColor: "#4169e1",
				image: "h.png",
				itemTitleColor: "#B800E6",
				items: [ { description: "VP, People & Organizational Capability",
					email: "helekram@name.com",
					groupTitleColor: "#4169e1",
					image: "j.png",
					itemTitleColor: "#B800E6",
					items: [ { description: "GM, Corporate Learning and Development",
						email: "michsamu@name.com",
						groupTitleColor: "#4169e1",
						image: "k.png",
						itemTitleColor: "#B800E6",
						phone: "203-250-0167",
						title: "Michael Samuels"
					} ],
					phone: "941-359-8120",
					title: "Helen Kramer"
				},
						{ description: "GM, Diversity & Inclusion",
							email: "tashwrig@name.com",
							groupTitleColor: "#4169e1",
							image: "l.png",
							itemTitleColor: "#B800E6",
							phone: "347-601-9047",
							title: "Tasha Wright"
						},
						{ description: "GM, HR",
							email: "elenmars@name.com",
							groupTitleColor: "#4169e1",
							image: "z.png",
							itemTitleColor: "#B800E6",
							phone: "309-765-7809",
							title: "Elena Marshall"
						},
						{ description: "GM, SMSG & International HR",
							email: "artibrya@name.com",
							groupTitleColor: "#4169e1",
							image: "x.png",
							itemTitleColor: "#B800E6",
							items: [ { description: "GM, HR International",
								email: "samupier@name.com",
								groupTitleColor: "#4169e1",
								image: "c.png",
								itemTitleColor: "#B800E6",
								phone: "469-392-2461",
								title: "Samuel Pierce"
							} ],
							phone: "315-538-4477",
							title: "Artie Bryan"
						},
						{ description: "GM, HR",
							email: "jennmend@name.com",
							groupTitleColor: "#4169e1",
							image: "v.png",
							itemTitleColor: "#B800E6",
							phone: "724-234-8576",
							title: "Jennifer Mendez"
						},
						{ description: "GM, Global Compensation & Benefits",
							email: "audrwhit@name.com",
							groupTitleColor: "#4169e1",
							image: "b.png",
							itemTitleColor: "#B800E6",
							phone: "602-725-4528",
							title: "Audra White"
						},
						{ description: "GM, Talent Acquisition and Engagement",
							email: "mablbatc@name.com",
							groupTitleColor: "#4169e1",
							image: "n.png",
							itemTitleColor: "#B800E6",
							phone: "903-381-3079",
							title: "Mable Batchelder"
						},
						{ description: "GM, HR",
							email: "terrwith@name.com",
							groupTitleColor: "#4169e1",
							image: "m.png",
							itemTitleColor: "#B800E6",
							phone: "231-924-8671",
							title: "Terry Witherspoon"
						},
						{ description: "GM, HR",
							email: "cyntdens@name.com",
							groupTitleColor: "#4169e1",
							image: "q.png",
							itemTitleColor: "#B800E6",
							phone: "503-419-7674",
							title: "Cynthia Denson"
						}
				],
				phone: "803-675-6422",
				title: "Kristen Nelson"
			}
	],
	phone: "352-206-7599",
	title: "David Dalton"
};

