//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DB_40114_codeclubModel", "FK_testreview_test", "test", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Asp.net25.Models.test), "testreview", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Asp.net25.Models.testreview), true)]

#endregion

namespace Asp.net25.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class model1Context : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new model1Context object using the connection string found in the 'model1Context' section of the application configuration file.
        /// </summary>
        public model1Context() : base("name=model1Context", "model1Context")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new model1Context object.
        /// </summary>
        public model1Context(string connectionString) : base(connectionString, "model1Context")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new model1Context object.
        /// </summary>
        public model1Context(EntityConnection connection) : base(connection, "model1Context")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<person> people
        {
            get
            {
                if ((_people == null))
                {
                    _people = base.CreateObjectSet<person>("people");
                }
                return _people;
            }
        }
        private ObjectSet<person> _people;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<test> test
        {
            get
            {
                if ((_test == null))
                {
                    _test = base.CreateObjectSet<test>("test");
                }
                return _test;
            }
        }
        private ObjectSet<test> _test;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<testreview> testreviews
        {
            get
            {
                if ((_testreviews == null))
                {
                    _testreviews = base.CreateObjectSet<testreview>("testreviews");
                }
                return _testreviews;
            }
        }
        private ObjectSet<testreview> _testreviews;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the people EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopeople(person person)
        {
            base.AddObject("people", person);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the test EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotest(test test)
        {
            base.AddObject("test", test);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the testreviews EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotestreviews(testreview testreview)
        {
            base.AddObject("testreviews", testreview);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_40114_codeclubModel", Name="person")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class person : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new person object.
        /// </summary>
        /// <param name="person_id">Initial value of the person_id property.</param>
        public static person Createperson(global::System.Int32 person_id)
        {
            person person = new person();
            person.person_id = person_id;
            return person;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 person_id
        {
            get
            {
                return _person_id;
            }
            set
            {
                if (_person_id != value)
                {
                    Onperson_idChanging(value);
                    ReportPropertyChanging("person_id");
                    _person_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("person_id");
                    Onperson_idChanged();
                }
            }
        }
        private global::System.Int32 _person_id;
        partial void Onperson_idChanging(global::System.Int32 value);
        partial void Onperson_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fname
        {
            get
            {
                return _fname;
            }
            set
            {
                OnfnameChanging(value);
                ReportPropertyChanging("fname");
                _fname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("fname");
                OnfnameChanged();
            }
        }
        private global::System.String _fname;
        partial void OnfnameChanging(global::System.String value);
        partial void OnfnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lname
        {
            get
            {
                return _lname;
            }
            set
            {
                OnlnameChanging(value);
                ReportPropertyChanging("lname");
                _lname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lname");
                OnlnameChanged();
            }
        }
        private global::System.String _lname;
        partial void OnlnameChanging(global::System.String value);
        partial void OnlnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String thumbnailFile
        {
            get
            {
                return _thumbnailFile;
            }
            set
            {
                OnthumbnailFileChanging(value);
                ReportPropertyChanging("thumbnailFile");
                _thumbnailFile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("thumbnailFile");
                OnthumbnailFileChanged();
            }
        }
        private global::System.String _thumbnailFile;
        partial void OnthumbnailFileChanging(global::System.String value);
        partial void OnthumbnailFileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String thumbnailExt
        {
            get
            {
                return _thumbnailExt;
            }
            set
            {
                OnthumbnailExtChanging(value);
                ReportPropertyChanging("thumbnailExt");
                _thumbnailExt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("thumbnailExt");
                OnthumbnailExtChanged();
            }
        }
        private global::System.String _thumbnailExt;
        partial void OnthumbnailExtChanging(global::System.String value);
        partial void OnthumbnailExtChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_40114_codeclubModel", Name="test")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class test : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new test object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static test Createtest(global::System.Int32 id)
        {
            test test = new test();
            test.id = id;
            return test;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_40114_codeclubModel", "FK_testreview_test", "testreview")]
        public EntityCollection<testreview> testreviews
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<testreview>("DB_40114_codeclubModel.FK_testreview_test", "testreview");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<testreview>("DB_40114_codeclubModel.FK_testreview_test", "testreview", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_40114_codeclubModel", Name="testreview")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class testreview : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new testreview object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static testreview Createtestreview(global::System.Int32 id)
        {
            testreview testreview = new testreview();
            testreview.id = id;
            return testreview;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> testid
        {
            get
            {
                return _testid;
            }
            set
            {
                OntestidChanging(value);
                ReportPropertyChanging("testid");
                _testid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("testid");
                OntestidChanged();
            }
        }
        private Nullable<global::System.Int32> _testid;
        partial void OntestidChanging(Nullable<global::System.Int32> value);
        partial void OntestidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> rate
        {
            get
            {
                return _rate;
            }
            set
            {
                OnrateChanging(value);
                ReportPropertyChanging("rate");
                _rate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rate");
                OnrateChanged();
            }
        }
        private Nullable<global::System.Int32> _rate;
        partial void OnrateChanging(Nullable<global::System.Int32> value);
        partial void OnrateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_40114_codeclubModel", "FK_testreview_test", "test")]
        public test test
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<test>("DB_40114_codeclubModel.FK_testreview_test", "test").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<test>("DB_40114_codeclubModel.FK_testreview_test", "test").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<test> testReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<test>("DB_40114_codeclubModel.FK_testreview_test", "test");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<test>("DB_40114_codeclubModel.FK_testreview_test", "test", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
