//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clientWCFBydll.HelloServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelloServiceReference.IHello")]
    public interface IHello {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHello/addSpec", ReplyAction="http://tempuri.org/IHello/addSpecResponse")]
        newWCFService.spec addSpec(newWCFService.spec spec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHello/getSpecs", ReplyAction="http://tempuri.org/IHello/getSpecsResponse")]
        newWCFService.spec[] getSpecs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHello/getSpecByName", ReplyAction="http://tempuri.org/IHello/getSpecByNameResponse")]
        newWCFService.spec getSpecByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHello/deleteSpec", ReplyAction="http://tempuri.org/IHello/deleteSpecResponse")]
        void deleteSpec(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelloChannel : clientWCFBydll.HelloServiceReference.IHello, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloClient : System.ServiceModel.ClientBase<clientWCFBydll.HelloServiceReference.IHello>, clientWCFBydll.HelloServiceReference.IHello {
        
        public HelloClient() {
        }
        
        public HelloClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public newWCFService.spec addSpec(newWCFService.spec spec) {
            return base.Channel.addSpec(spec);
        }
        
        public newWCFService.spec[] getSpecs() {
            return base.Channel.getSpecs();
        }
        
        public newWCFService.spec getSpecByName(string name) {
            return base.Channel.getSpecByName(name);
        }
        
        public void deleteSpec(string id) {
            base.Channel.deleteSpec(id);
        }
    }
}
